### ISSUE TITLE
How stable is MvRx at the moment, how much will API change?

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#107]
I'm building average size (~40 screens) greenfield app now and I need to deliver it quickly. I like the idea of `MvRx`, with `Epoxy` it saves so much boilerplate. Thank you for your work!
Version 0.5 scares me a bit. How stable is `MvRx` at the moment and how much will API change in the future?

**Comment by gpeal** [comment]
@qbait It is currently used in well over 200 screens at Airbnb and would very much like to avoid making major API changes going forward as doing so would be painful for Airbnb as well.

We only plan on doing this with a good reason and a clear migration plan so I would consider this more stable than your average 0.5.

**Comment by gpeal** [comment]
cc @elihart @BenSchwab @hellohuanlin
