### ISSUE TITLE
findViewById in models

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#108]
In `todomvrx` and `sample`you use `findViewById` in models. Is there any reason behind this additional mapping instead of importing views  directly with `Kotlin`?

Instead of writing this one:
```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class Header @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr) {

    private val titleView by lazy { findViewById<TextView>(R.id.title) }

    init {
        inflate(context, R.layout.header, this)
    }

    @TextProp
    fun setTitle(title: CharSequence?) {
        titleView.text = title
    }
}
```

write this one (assuming that I have `R.id.titleView` instead of `R.id.title`)

```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class Header @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr) {

    init {
        inflate(context, R.layout.header, this)
    }

    @TextProp
    fun setTitle(title: CharSequence?) {
        titleView.text = title
    }
}
```

**Comment by jQrgen** [comment]
Where does the titleView field come from in the latter code example?

**Comment by qbait** [comment]
from `xml`. Assuming that I have `R.id.titleView` instead of `R.id.title`

**Comment by gpeal** [comment]
@qbait Yes, if you go forward on the backstack and return to the Fragment, the view will be destroyed and recreated but the lazy value will have the original view. I add these [ViewBinders](https://gist.github.com/gpeal/14d9644387631f96fb7e2dec3d56e052) in my apps and call `clear()` in `onDestroyView` so it becomes

`val myView: TextView by bindView(R.id.my_view)`
