### ISSUE TITLE
What is the role of MvRxLifecycleAwareObserver in MvRx?

### ISSUE THREAD

**Issue by littleGnAl** [airbnb/MvRx#114]
I see this issuse [#15](https://github.com/airbnb/MvRx/issues/15), but I don't understand the specific reason. In the absence of `MvRxLifecycleAwareObserver`, if the state changes, the direct subscribe `stateStore.observable` should also deliver the new state. In my opinion, the role of `MvRxLifecycleAwareObserver` is in order to deliver the state after the `Fragment/Activity` is restarted, instead of delivering the state every time the `stateStore.observable` changes, reduce the unnecessary `invalidate`. If my understand is wroing, please correct me. Thank you.

**Comment by gpeal** [comment]
@littleGnAl This is correct. The ViewModel will be "alive" from the time it is created until your Fragment is permanently destroyed meaning it is still around if your Fragment is on the back stack or is rotating.  However, you certainly don't want updates being delivered to a screen when it isn't started. Not only would that not make sense but it could lead to crashes where there isn't even a view or a context.
