### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#116]
According to this https://github.com/airbnb/epoxy/issues/562#issuecomment-427986157 `Epoxy` for iOS is coming soon, are you planning to open source iOS MvRX as well?
Would be great to have consistent architecture on both platforms.

Thank you for your awesome work!

**Comment by hellohuanlin** [comment]
@qbait Yes we do have plan to open source iOS version. They will have consistent architecture since ios and android mvrx teams work very close together.

**Comment by qbait** [comment]
That's great news, thank you.

**Comment by qbait** [comment]
Any news guys? :)

**Comment by gpeal** [comment]
@hellohuanlin ^

**Comment by hellohuanlin** [comment]
@qbait Yes. Things are going well. We currently have 4 pilot teams in Airbnb trying out MvRx on iOS and the feedback has been pretty positive. We should expect it open-sourced soon.

**Comment by hooliooo** [comment]
@qbait In the meantime, while you wait for MvRx iOS from Airbnb, FFUF created a version for iOS
heavily based MvRx and Epoxy

https://github.com/feilfeilundfeil/Cyanic

**Comment by Dwite** [comment]
@hellohuanlin just curious do you have any new information about MvRx iOS version? 👍

**Comment by Zoha131** [comment]
Is there any plan for kotlin multiplatform? or any update on MvRx iOS version?

**Comment by rayalarajee** [comment]
Any update on ios version.

**Comment by kaushalyap** [comment]
@hellohuanlin How is the iOS version going on?

**Comment by elihart** [comment]
I believe the iOS version is dead. no plans for ios or multiplatform

**Comment by rakuyoMo** [comment]
> I believe the iOS version is dead. no plans for ios or multiplatform

If this is true, it's really sad.

**Comment by idrisadetunmbi** [comment]
Dropping by to know if there has been a change of mind with KMM?

**Comment by gpeal** [comment]
With the upcoming 3.0 release, there will be a `mavericks-common` jvm artifact that brings us one step closer. It hasn't been a top priority for Airbnb or Tonal, however.
