### ISSUE TITLE
Subscriptions need to happen in `onCreate`.

### ISSUE THREAD

**Issue by BenSchwab** [airbnb/MvRx#118]
When a fragment is added to the backstack, and then resumed, almost all lifecycles besides `onCreate `will be called again. If you call `subscribe` or `selectSubscribe` in a different lifecycle, such as `onViewCreated` or `onActivityCreated` everytime you resume your fragment you will create a new subscription, which is almost certainly not intended.

We need to:
1) Update MvRx documents to state that all subscriptions should be made in `onCreate`.
2) Update MvRx demos to follow this rule.

http://vinsol.com/blog/wp-content/uploads/2014/08/fragment_lifecycle.png

**Comment by justsosoxd** [comment]
Sometimes having all subscriptions in `onCreate` is really annoying since views have not been created here which means everything used in the callback need to be a member of the fragment instead of a local variable. And it's also error prone cuz this is not guaranteed by any compile-time checking .

Why not try using `getViewLifecycleOwner` instead of `this` for a fragment?  This only requires upgrading support library version to 28.

**Comment by gpeal** [comment]
@justsosoxd That should be okay because the subscription will only get called when the fragment is in the `STARTED` lifecycle.

**Comment by gpeal** [comment]
@BenSchwab What is actionable here?

**Comment by ubuntudroid** [comment]
@justsosoxd wouldn't using `getViewLifecycleOwner()` possibly make things even worse? The view lifecycle can be even shorter in case of detached Fragments than the one of the Fragment itself as per the documentation.

**Comment by BenSchwab** [comment]
@gpeal We could start logging a warning (or crash) if you subscribe after `onCreate`? Or maybe we could keep a list of active subscribers references and no-op if one already exists? (I would need to look into how references work on lambdas, not sure if this is possible.)

**Comment by justsosoxd** [comment]
@ubuntudroid If I get it right, the problem we need to resolve here is duplicated subscription when fragments are added to backstack then resumed. view lifecycle can avoid this problem as the subscription will be disposed when fragment is added to backstack. why would it make things worse?

**Comment by ubuntudroid** [comment]
@justsosoxd uh, I think I got the problem statement wrong. After rereading I think you are actually right. Sorry for the confusion!

**Comment by BenSchwab** [comment]
I think we can change subscriptions made after onCreate to use `getViewLifecycleOwner` .

Need to add tests, but this is what it would look like: https://github.com/airbnb/MvRx/commit/b76d71bad3a86f4f921adaa5af6cded2713e34ab

**Comment by gpeal** [comment]
@BenSchwab How would using the view lifecycle owner solve this? Wouldn't you still have duplicate subscriptions?

**Comment by BenSchwab** [comment]
No, I don't think so, as the subscriptions would be disposed in `onDestroyView` so they can be safely recreated in `onCreateView`.

**Comment by gpeal** [comment]
@BenSchwab Yeah, makes sense. Want to take a stab at it?
