### ISSUE TITLE
HTTP Status 202 gives me Async Fail

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#120]
I'm using Retrofit, it gives me a response with status code 202. However, when I'm watching my Async request it gives me Fail?

I was sure that status codes from 200 to 300 are by default Success?
What's the best way to make it return Success?

**Comment by gpeal** [comment]
@qbait MvRx doesn't know anything about http status codes. It just maps onError in the rx stream to fail so I'd suggest checking your Retrofit/okhttp configuration to see why that is happening.
