### ISSUE TITLE
Changing item in list

### ISSUE THREAD

**Issue by anasanasanas** [airbnb/MvRx#122]
let's say we have a List in the state 
that list contains some objects 
we did not add or delete any object from the list 
if we change some variables value in any of these objects and then set the state.
the observer does NOT get any new emission.

**Comment by hellohuanlin** [comment]
@anasanasanas 
you should use immutable classes (e.g. data class), or at least classes with a properly defined hash function (instead of just memory address hash), so that when you update a variable in the object, its hash is also updated.

**Comment by gpeal** [comment]
This is correct, the hashCode of your objects must be different.
