### ISSUE TITLE
support view model creator extension for activity?

### ISSUE THREAD

**Issue by bng86** [airbnb/MvRx#127]
I found 3 extension for view model creator
fragmentViewModel, existingViewModel, activityViewModel
but it only support fragment scope

**Comment by bernaferrari** [comment]
As far as I remember, Google is discouraging multiple activities, the way everything should be done is on fragments.

**Comment by gpeal** [comment]
@bng86 `activityViewModel` scopes it to an Activity so that if you request it from another Fragment, you'll get the same instance. It is the mechanism with which you can share data across different Fragments, not intended to be used in an Activity itself.

**Comment by Aexyn** [comment]
I am planning to use MvRx in our projects. But it has existing Activities in Java. I am writing new code by extending that class in new Kotlin file I created and wanted to use MvRx in that class. So technically it is not possible? As MvRx viewModels doesn't support Activities. Am I right? Is there any way to use viewModels in that Scenario?

**Comment by bernaferrari** [comment]
Yeah, it supports. Check activityViewModel.

**Comment by gpeal** [comment]
@Aexyn Instead of writing feature code in an Activity, make your Activity just add a Fragment then do your work there.

**Comment by Aexyn** [comment]
@bernaferrari Okay.. I will check it.. and get back to you :)

@gpeal I would love to. But there are some limitations currently and that's why I cannot.  Hence stuck in the situation and finding answers.

**Comment by gpeal** [comment]
@Aexyn You can create your own ViewModel instance and subscribe manually. You'll have to figure out how to handle persistence and configuration changes though.

**Comment by Aexyn** [comment]
@gpeal can you please provide any link to sample or anything close related? Any help would be appreciated. Thankyou :)

**Comment by gpeal** [comment]
@Aexyn for one non-public project, I created a ViewModel as a dagger singleton and injected it where necessary.
