### ISSUE TITLE
[Open Question] BaseMvRxViewModel first class coroutine support

### ISSUE THREAD

**Issue by gpeal** [airbnb/MvRx#130]
We've already made MvRx work great with rxjava by adding things like `disposeOnClear` and `execute`.
I think we could add first class support for coroutines by:
* Making BaseMvRxViewModel a CoroutineScope
* Making an `execute` on `Deferred<T>` which would look something like (untested code):
```
    protected suspend fun <T> Deferred<T>.execute(reducer: S.(Async<T>) -> S) {
        setState { reducer(Loading()) }
        try {
            val value = await()
            setState { reducer(Success(value)) }
        } catch (e: Exception) {
            setState { reducer(Fail(e)) }
        }
    }
```

@hellohuanlin @elihart @BenSchwab @ATizik

**Comment by ATizik** [comment]
It's preferable to avoid Deferred, maybe it can look like this?

`protected suspend fun <T> (suspend ()->T).execute(reducer: S.(Async<T>) -> S) {
    setState { reducer(Loading()) }
    try {
        val value = this()
        setState { reducer(Success(value)) }
    } catch (e: Exception) {
        setState { reducer(Fail(e)) }
    }
}`

Also when [this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/254) is resolved, additional `execute` extensions can be added

**Comment by gpeal** [comment]
@ATizik Why is it preferable to avoid `Deferred`?

**Comment by ATizik** [comment]
@gpeal 
In idiomatic coroutine code instead of
`fun foo(): Deferred<Int> = TODO()`
it's better to use
`suspend fun foo(): Int = TODO()`

[Here](https://github.com/Kotlin/kotlinx.coroutines/issues/342#issuecomment-383841713) is more info

**Comment by gpeal** [comment]
@ATizik Makes sense. Some things like the [retrofit coroutines adapter](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter) will return `Deferred<T>` though.

**Comment by razilsh** [comment]
@gpeal Retrofit now support suspend functions 😄

**Comment by elihart** [comment]
it would be great to do this once the new Jetpack provided ViewModel coroutine scope is out of beta.

It seems reasonable to provide an extension to both `Deferred<T>` and (suspend ()->T)`.

I think we should also have the function return a `Job` so the user can cancel it if needed. In the try/catch block do we need to handle CancellationException any differently if the job is canceled, and we don't want it to trigger the fail state?

I'd like to see us make the basic case of running basic processing in the viewmodel as simple as possible. Something like
```kotlin
class MyViewModel {
     init {
           async {
                   lookupSomeData()
          }.execute {
               copy(myData = it)
          }
    }
}
```

**Comment by kaushalyap** [comment]
@gpeal Hello, the problem I have  with MvRx is that it uses RxJava as a dependency. If you are also using coroutines in your app, then this increase your apk/bundle size. What's your thoughts on this?

**Comment by elihart** [comment]
It would be nice to have a version with only coroutines and no Rx for that reason, but I think it may be non trivial, since the whole subscription system is based on rxjava so it isn't as simple as swapping out the state store.

Can you say how large the APK size increase is after the RxJava dependency with R8/Proguard properly minifying it?

**Comment by gpeal** [comment]
In progress with the work on 2.0
