### ISSUE TITLE
Documentation for disposeOnClear()

### ISSUE THREAD

**Issue by jQrgen** [airbnb/MvRx#131]
Hey

How does disposeOnClear work?

I cannot find any documentation for it.

![screenshot 2018-11-01 at 15 35 10](https://user-images.githubusercontent.com/3964957/47861924-e1ca8880-ddeb-11e8-9f3f-6c79f3d9c4a7.png)
![screenshot 2018-11-01 at 15 37 43](https://user-images.githubusercontent.com/3964957/47862034-1dfde900-ddec-11e8-99d9-2dbae32bea95.png)

Thanks

**Comment by littleGnAl** [comment]
@jQrgen You can find the code inside the `BaseMvRxViewModel`
