### ISSUE TITLE
Async subscriber randomly skipped

### ISSUE THREAD

**Issue by abaffym** [airbnb/MvRx#132]
Hey. I'm having an issue when subscribing to an Async with the `selectSubscribe` method in a viewmodel. When the Async (i.e. network call) fails, the subscriber is randomly not called.

Here is a simple demo that demonstrates the issue. The `onAsyncChanged` gets randomly skipped eventhough the execute reducer is called.

```kotlin
data class MainState(
    val async: Async<Unit> = Uninitialized
) : MvRxState

class MainViewModel(
    initialState: MainState
) : BaseMvRxViewModel<MainState>(initialState) {

    init {
        selectSubscribe(MainState::async, ::onAsyncChanged)
    }

    fun callAsync() = Single.fromCallable<Unit> { throw IllegalArgumentException() }.execute {
        copy(async = it)
    }

    private fun onAsyncChanged(async: Async<Unit>) {
        Log.d("MainViewModel", "$async")
    }
}

class MainFragment : BaseMvRxFragment() {

    private val viewModel: MainViewModel by fragmentViewModel()

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View =
        inflater.inflate(R.layout.fragment_main, container, false)

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        btn_async.setOnClickListener { viewModel.callAsync() }
    }

    override fun invalidate() {

    }
}
```

Any ideas?

UPDATE: I just figured it out. 

The problem is caused by the `distinctUntilChanged` operator on the state observable in the `RealMvRxStateStore`. 
Sometimes, the `Loading<Unit>` and `Fail<Unit>` state changes are flushed separately in the `flushSetStateQueue()` method, but sometimes they get folded together, so there is no distinction between the previous and the new state.

I've managed to solve it by delaying the observable call.

If this is the expected behaviour, feel free to close the issue.

**Comment by gpeal** [comment]
@abaffym This is the expected behavior. States are coalesced for performance reasons.
