### ISSUE TITLE
RecyclerView scroll position not properly restored

### ISSUE THREAD

**Issue by iMvBremen** [airbnb/MvRx#134]
It seems that the RecyclerView scroll position is not properly restored (from a screen rotation for example). 

My guess is that this is due to the [`postInvalidate()`](https://github.com/airbnb/MvRx/blob/master/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxFragment.kt#L29) called in `onStart()` in the `BaseMvRxFragment` (in case no `ViewModel` is used, but the same idea applies for when `ViewModels` are used as `postInvalidate()` is called there as well). This results in a message being pushed onto the queue of the handler as seen [here](https://github.com/airbnb/MvRx/blob/master/mvrx/src/main/kotlin/com/airbnb/mvrx/MvRxView.kt#L33). This message is likely to be handled after a call to `Fragment#onViewStateRestored()`, where the scroll position is restored. This means that the scroll position is restored for a `RecyclerView` that doesn't have items yet, thus scroll position can't be restored as it's not scrollable yet?

Shouldn't the first call to `invalidate()` be called directly (synchronously) to set up the initial state of the `Views` before the `Fragment` is visible? I've created my own `BaseMvRxFragment` that calls `invalidate()` directly in `onActivityCreated()`, which is the last callback before `onViewStateRestored()` is called (see [lifecycle](https://github.com/xxv/android-lifecycle)): 

```kotlin
abstract class BaseMvRxDialogFragment : DialogFragment(), MvRxView {

    override val mvrxViewModelStore by lazy { MvRxViewModelStore(viewModelStore) }

    override fun onCreate(savedInstanceState: Bundle?) {
        mvrxViewModelStore.restoreViewModels(this, savedInstanceState)
        super.onCreate(savedInstanceState)
    }

    override fun onSaveInstanceState(outState: Bundle) {com.airbnb.mvrx.BaseMvRxFragment
        super.onSaveInstanceState(outState)
        mvrxViewModelStore.saveViewModels(outState)
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        // Calling invalidate() directly so that View state can be restored
        invalidate()
    }
}
```

Note that this is just my idea. Please tell me if I'm wrong and/or doing something wrong here. Otherwise, what's the recommended solution for this?

**Comment by gpeal** [comment]
@iMvBremen Can you create a sample project that repros this?

**Comment by elihart** [comment]
afaik there is no way via `MvRxView` or fragment lifecycle to get a hook between view being created and view state restored. In our own app out base fragment calls `invalidate` in `onActivityCreated` so we don't have any problems.

Unless we want to add a new callback to `MvRxView` that must be implemented to provide that hook, I think it's easy enough to have the base fragment manually call invalidate. Do we need to update the sample to show this?

**Comment by iMvBremen** [comment]
@elihart Thanks for the reply. I'm also calling `invalidate()` in `onActivityCreated()`, which indeed fixes this 'issue'. Just out of curiosity: What is the idea behind `postInvalidate()` in the [`BaseMvRxFragment`](https://github.com/airbnb/MvRx/blob/77cb6063be84951156ce21b247356ead432810fe/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxFragment.kt#L29)'s `onStart()`? Especially if you guys call `invalidate()` in your own base Fragment as well. Wouldn't it be easier to change the `BaseMvRxFragment` to do this by default? Unless there's a good reason that `postInvalidate()` should be called instead, of course. 

@gpeal I expect the same thing to happen in the [ToDo MvRx sample](https://github.com/airbnb/MvRx/tree/master/todomvrx) if it has enough items to scroll to be honest, but I haven't tested this. Don't think a sample project is necessary after https://github.com/airbnb/MvRx/issues/134#issuecomment-440733128?

**Comment by elihart** [comment]
We don't want to force everyone to use our sample MvRxFragment - by putting `postInvalidate` into the view model subscription it's guaranteed to work with any MvRxView. That flexibility comes at a cost of not being as perfect for the fragment use case

**Comment by jpventura** [comment]
@elihart given `postInvalidate` should not be enforced, may we close this issue?
