### ISSUE TITLE
Async can't represent one-off events well

### ISSUE THREAD

**Issue by luozejiaqun** [airbnb/MvRx#137]
As #80 #121 mentioned, I think the root cause is that the Async can't represent one-off events well. I can use `asyncSubscribe` to fire one-off event, but the Async's state stays the same after the event. I run into a case where this can cause a problem.
```
interface InitialState : MvRxState {
    val repoAsync: Async<Any>
}

abstract class BaseFragment : BaseMvRxFragment() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel.subscribe { state ->
            if (state.repoAsync is Loading) {
                startLoading()
            } else {
                stopLoading()
                if (state.repoAsync is Fail) {
                    handleFail((state.repoAsync as Fail<Any>).error)
                }
            }
        }
    }

    private fun handleFail(throwable: Throwable) {
    //showing toasts/snackbars
    }
}
```

All my states implements InitialState , the `repoAsync` represent all the repository request's state. This work well for me, but it has a problem when sharing ViewModel between fragments, say the first fragment has failed in one request and shows the toasts/snackbars, then go to the second fragment, the  toasts/snackbars show again when the fragment created.
So I think if Async can be reseted automatically when Success/Fail is consumed, that would be great. Am I think right? And is it the right way to handle all the loading and fail?

[ADD] My issue is not that I don't know how to fire the one-off event or how to avoid the one-off event to show again, but the fact that MvRx use `Async`'s state to represent the one-off event, however, `Async`'s state stay the same after the one-off event which I think is not a good way.

**Comment by littleGnAl** [comment]
@luozejiaqun do your `viewModel` delegate by the `activityViewModel()`?

**Comment by luozejiaqun** [comment]
> @luozejiaqun do your `viewModel` delegate by the `activityViewModel()`?

yes

**Comment by littleGnAl** [comment]
@luozejiaqun I think you should use `asyncSubscribe(InitialState:: repoAsync, ..., ...) ` instead `subscribe `, you can dig into the source code, the `uniqueOnly = false` by default, so the state will be re-emit when the `onStart` lifecycle is triggered.

**Comment by gpeal** [comment]
@luozejiaqun As @littleGnAl mentioned, I think asyncSubscribe with `uniqueOnly = true` will fix this. Can you close this if it does?

**Comment by luozejiaqun** [comment]
@gpeal `uniqueOnly = true` only works when one subscriber already `subscribe` the state, when we `subscribe` a new subscriber, current state will send to it immediately. In my case, the second fragment must `subscribe` the state again to show loading and toast/snackbar. The fundamental thing is that since the `State`'s properties represent the whole UI, there is something like toast/snackbar the `State`'s properties(the `Async` ) can't represent well.

**Comment by elihart** [comment]
Async isn't intended to represent one-off events necessarily, and I don't imagine it'll be changed unless someone has a strong proposal.

We are targeting the common case with Async, I don't think we should make the common case harder so that your rare case is handled easier, when it shouldn't be too hard for you to add a property to your state to track whether you have handled the failure.

I would be interested in hearing any proposals for how to change Async without harming the common case

**Comment by luozejiaqun** [comment]
@elihart Thanks

**Comment by kajalgondaliya** [comment]
@luozejiaqun Did you get any solution about your issue? If yes then please provide step How to manage?

**Comment by luozejiaqun** [comment]
@kajalgondaliya There are many ways to solution the issue. The easiest way is resetting Async to `Uninitialized` every time you consume it.

**Comment by ursusursus** [comment]
@luozejiaqun if you reset it, then view might not even see the success
