### ISSUE TITLE
Exposing MvRxStateStore directly

### ISSUE THREAD

**Issue by hellohuanlin** [airbnb/MvRx#140]
I think it's more flexible if we can expose MvRxStateStore, so that developers who favor composition over inheritance can still use it without subclassing MvRx. It also helps the developers who only wanna use the state management part of the library.

**Comment by gpeal** [comment]
@hellohuanlin What is the use case for that? Exposing it also means that it becomes a public API.

Also of note is that it's likely to change in the near future if we upgrade it to [use coroutines](https://github.com/airbnb/MvRx/pull/84)).

**Comment by hellohuanlin** [comment]
I mean we can expose the state, without exposing what's private inside the state. It can still be coroutines if we want. 
The use case is that, some developers only want to use mvrx for redux style state management, and dislikes having to inherit from MvRx view model.

**Comment by gpeal** [comment]
@hellohuanlin What is wrong with using ViewModel but managing its lifecycle on your own?

**Comment by gpeal** [comment]
@hellohuanlin bump

**Comment by hellohuanlin** [comment]
@gpeal Could you explain more? I am not sure if I follow.

**Comment by gpeal** [comment]
@hellohuanlin I would prefer to keep MvRx small and opinionated rather than opening it up to much more flexible use cases. I think its opinionated nature is one of the reasons it has been successful.

**Comment by hellohuanlin** [comment]
@gpeal let me think about it. I have been thinking about wrapping MvRx for my module, and see if i can  avoid inheritance in my wrapper API (since I am only using the state management part of MvRx)

**Comment by gpeal** [comment]
@hellohuanlin any update here?

**Comment by gpeal** [comment]
@hellohuanlin I'm going to close this. Feel free to reopen it if needed.
