### ISSUE TITLE
data refresh problem

### ISSUE THREAD

**Issue by leeyun** [airbnb/MvRx#146]
The data requested by the interface has not changed. How to update the UI
```
 .execute {
                    copy(result = it, logs = (it()?.orderList ?: emptyList()), page = 2, refresh = refresh + 1)
                }
```
How do I notify the UI when the result have not changed?

**Comment by luozejiaqun** [comment]
MvRx can't help you, but you can use `LiveData` to notify the UI.

**Comment by leeyun** [comment]
thank
