### ISSUE TITLE
CompositeDisposable in BaseMvRxViewModel will accumulate Disposable, won't clear until ViewModel.onClear() called

### ISSUE THREAD

**Issue by poooower** [airbnb/MvRx#156]
As the description in title, i think it should expose a method to remove disposed Disposables;
Or there is a mechanism to clear all disposed Disposables automatically

**Comment by gpeal** [comment]
@poooower This is the expected behavior as `onCleared` is the only lifecycle for a ViewModel after being created. If you need to dispose things based on another trigger (like logout or something) then you can manage that yourself.

**Comment by gpeal** [comment]
@poooower Ah, I see what you are saying. However, I don't think that its overhead is significant and would only apply to completable streams. Technically fetchNextPage could return multiple times so you never really know when it is complete.
