### ISSUE TITLE
 How to reset Async request's state required in login screen?

### ISSUE THREAD

**Issue by kajalgondaliya** [airbnb/MvRx#158]
Login Screen
-    If user enter wrong username and password
-    Click on Login button
-    Getting error in onFail method call (Working perfect)
-    Then again user enter wrong password
-    Click on login button
-    Here required call again "onFail method" 

`    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        viewModel.selectSubscribe(LoginState::request) {
            when (it) {
                is Loading -> {
                    Timber.d("Loading..")
                } 
                is Success -> {
                    Timber.d("API call success")
                } 
                is Fail -> {
                    Timber.d("errorr " + it.toString())
                    val loginError = it.error.prettyLoginMessage()
                    alert(loginError!!, "Failure") {
                        okButton {}
                    }.show()
                }
            }
        }
    }
`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41906092/50465711-f9268c00-09be-11e9-9d4e-1172181776e0.gif)

**Comment by poooower** [comment]
the reason is Fail is equal, so it will not be emitted again.
one solution is make login fail exception different every time, such as add timestamp as part of message

https://github.com/airbnb/MvRx/issues/142

**Comment by gpeal** [comment]
@poooower It wouldn't be the same if you use execute because it will go back through the loading state.

**Comment by poooower** [comment]
@gpeal, as the discussion in https://github.com/airbnb/MvRx/issues/142

**Comment by gpeal** [comment]
@poooower We are going to remove the state coalescing. Will that resolve this? If so, let's close this issue 😄
