### ISSUE TITLE
SparseArray in state

### ISSUE THREAD

**Issue by luozejiaqun** [airbnb/MvRx#166]
As I mentioned in #79. MvRx enforces immutability of state, so we can't use `SparseArray` in state. Suggestion of MvRx is using  immutable list instead, but that would loss the performance advantages of SparseArray. I put SparseArray in `LiveData` and remove it from the state, but that can be buggy. So what's the best way to use SparseArray?

**Comment by gpeal** [comment]
@luozejiaqun Did you benchmark immutable lists in Kotlin to determine that they are too slow? Your list operations should also be off the main thread which is part of the reason we did it (relevant for your other issue).

**Comment by luozejiaqun** [comment]
@gpeal I didn't benchmark the immutable lists. How to make SparseArray works is on top of my head when I meet the problem. Maybe immutable lists don't perform that bad, but SparseArray is more simple to use. So I finally use LiveData. Is it the cost of immutability? We may sacrifice performance or ease of use.

**Comment by jinxinzheng** [comment]
MvRx enforces immutability in `assertImmutability` but it only checks for a few direct types. 

If you have to use it without modifying MvRx, `SparseArray` is a `Clonable`, so you can wrap it in a container class, and make a clone of it every time you want to update it.

For a quick example (I did not test it, just figured it in a few minutes),

```kotlin
class WrappedSparseArray<T>(val value: SparseArray<T>) {
    fun copy(): WrappedSparseArray<T> {
        return WrappedSparseArray(value.clone())
    }
}
```

then in your ViewModel

```kotlin
data class State(val foo: WrappedSparseArray<Int>) : MvRxState

class YourViewModel(initialState: State) : BaseMvRxViewModel<State>(initialState) {
    fun updateFoo(block: (SparseArray<Int>) -> Unit) =
        setState{ copy(foo = foo.copy().apply { block(value) }) }
}
```

And do never directly modify the `SparseArray` itself.  Instead use `updateFoo` to make modifications like this

```kotlin
viewModel.updateFoo { sparseArray ->
    //sparseArray.put
    //sparseArray.remove
    //sparseArray.append
    ...
}
```

**Comment by gpeal** [comment]
@luozejiaqun What are you trying to do exactly? Can you include a code snippet?

**Comment by luozejiaqun** [comment]
@jinxinzheng Is it more simple to extend SparseArray and override `equals` and `hashCode`. Make it not 
 equal every time we update it. PS. Are you a Chinese guy? Your name sounds like.

**Comment by gpeal** [comment]
@luozejiaqun It sounds like you have a couple of options here. I'm going to close the issue.
