### ISSUE TITLE
MvRxViewModelFactory type args swapped

### ISSUE THREAD

**Issue by shaishavgandhi05** [airbnb/MvRx#175]
The code is: `interface MvRxViewModelFactory<VM : BaseMvRxViewModel<S>, S : MvRxState>`

However, the Wiki has it swapped. `MvRxViewModelFactory<MyState, MyViewModel>`

Unfortunately, I make a PR for the wiki.

**Comment by gpeal** [comment]
@shaishavgandhi05 Fixed. Thanks!
