### ISSUE TITLE
Proguard obfuscate MvRxViewModelFactory subclasses

### ISSUE THREAD

**Issue by lirik16** [airbnb/MvRx#185]
In the version [0.7.2](https://github.com/airbnb/MvRx/tree/v0.7.2), I've got a crash with enabled Proguard
`Caused by: java.lang.IllegalArgumentException: c takes dependencies other than initialState. It must have companion object implementing MvRxViewModelFactory with a create method returning a non-null ViewModel.` 
It looks like the problem in the [MvRxViewModelProvider.createViewModel](https://github.com/airbnb/MvRx/blob/v0.7.2/mvrx/src/main/kotlin/com/airbnb/mvrx/MvRxViewModelProvider.kt#L60) because Proguard obfuscates Companion object.
`-keep class * implements com.airbnb.mvrx.MvRxViewModelFactory { *; }` works for me to fix the problem.

**Comment by gpeal** [comment]
@BenSchwab FYI

**Comment by chrisbanes** [comment]
I've also just hit this. The following is a less 'keep everything' Proguard rule:

`-keepnames class * implements com.airbnb.mvrx.MvRxViewModelFactory`

**Comment by tasomaniac** [comment]
We also realized a R8 issue yesterday. App crashes on startup. Out stacktrace looks more like the one in the old issue. 🤔

https://github.com/airbnb/MvRx/issues/126

**Comment by chrisbanes** [comment]
@tasomaniac I'm using R8 too. Try these: https://github.com/chrisbanes/tivi/blob/master/app/proguard-rules.pro#L137
