### ISSUE TITLE
Sample App in MvRx/sample does not build succesfully

### ISSUE THREAD

**Issue by vedantroy** [airbnb/MvRx#193]
I downloaded the sample app from MvRx/sample. However, when I tried to build it in Android Studio, I got the following error: "ERROR: Plugin with id 'com.android.application' not found.".

Additional Info:

I also noticed that Android studio only lists one build.gradle file (the project build.gradle file) under "Gradle Scripts' and the project build.gradle file seems to be switched with the app-level build.gradle file. Also, when I first loaded the project, Android Studio prompted me to create a "gradle-wrapper.properties" file because apparently it was missing.

Update: It seems like I need to download the entire repository in order to build the sample app?

**Comment by gpeal** [comment]
@vedantroy Correct. The root gradle project is the root directory of the repo. You have to import that.
