### ISSUE TITLE
MvRxLifecycleAwareObserver breaks unit testability

### ISSUE THREAD

**Issue by tasomaniac** [airbnb/MvRx#198]
Currently all kind of `subscribe` and `asyncSubscribe` methods strongly depend on `MvRxLifecycleAwareObserver` which then depends on Android APIs. 

Example call:

```
viewModel.asyncSubscribe(LoginState::token, onSuccess = {
    navController.navigate(R.id.open_search)
 })
```

It is almost impossible to unit test the implementation of functions given into `asyncSubscribe` and its siblings. Basically in unit tests, the fragment lifecycle will never be in resumed state and that's why `MvRxLifecycleAwareObserver` never calls the `subsriber` function.

**Comment by rom4ek** [comment]
Agree here, looks like [this](https://github.com/airbnb/MvRx/blob/b4417f39b815c3a79dfaa660a9fe5c2c7ba00b84/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt#L258) needs to be exposed, or at least be `VisibleForTesting` for that.

**Comment by tasomaniac** [comment]
@rom4ek Technically the link you mentioned make sense. I can even use that function right now since it is only protected by lint and is public. 

But since I'm testing the view layer, my code uses the one defined in `MvRxView` and that automatically retrieves the lifecycleOwner from the given Fragment.

**Comment by rom4ek** [comment]
Yeah, that's what I meant - it should be exposed via extension in `MvRxView` I guess.

**Comment by tasomaniac** [comment]
Another idea to solve this is to introduce this functionality into already existing `TestRule`: https://github.com/airbnb/MvRx/blob/master/testing/src/main/kotlin/com/airbnb/mvrx/test/MvRxTestRule.kt

This test rule would hook up into internals of MvRx and replace `MvRxLifecycleAwareObserver` with a regular one which will always subscribe in unit tests.
