### ISSUE TITLE
Sample App has issue with TLS1.2 on <= Android 4.4

### ISSUE THREAD

**Issue by ghost** [airbnb/MvRx#199]
On Android 4.1.x and up until 4.4 TLS1.2 is not switched on by default. So if you run Sample App on Android 4.4 (try it on emulator) and below you can see that url https://icanhazdadjoke.com/ throw error due to TLS1.2 support issue. 

Retrofit2 using OkHttpClient and some suggestions how to resolve it described [here](https://github.com/square/okhttp/issues/2372). The easiest way is to use Google Play Services together with `ProviderInstaller.installIfNeeded` but it will force to apply MultiDex because Sample App already close to 65,536 methods. Another way is to provide custom SocketFactory.

In addition you didn't handle onFail in subscriber for RandomDadJokeState, so there no any errors showing in UI if request is failed.

**Comment by tasomaniac** [comment]
What about just making the sample with minSdk=21?
