### ISSUE TITLE
How to make a Settings screen with view animation?

### ISSUE THREAD

**Issue by bernaferrari** [airbnb/MvRx#201]
I'm having trouble thinking how to make a settings screen using MvRx + Epoxy. It was [really simple/easy to work with Groupie](https://github.com/bernaferrari/SDKMonitor/blob/58cfc8119f5465fd373e9f20942e2ec4fd9e47e9/app/src/main/java/com/bernaferrari/sdkmonitor/settings/SettingsFragment.kt#L80), but I can't figure out how to make Epoxy+MvRx work with it.

I want to see content changing/being animated, without the "row being replaced/diffied" which typically happens. I was able to make Epoxy work by changing params inside the clickListener, like:                                                         v.item_switch.isChecked = true.

However, when dealing with MvRx, I have to deal with the ViewModel. What should I put there? A bunch of [observable  SharedPreferences](https://github.com/afollestad/rxkprefs)? Nothing? Don't use MvRx for this scenario?

<img src="https://user-images.githubusercontent.com/351125/53041699-660c4e80-3463-11e9-9e34-4e7a4d22abe7.gif" width="250" />

<img src="https://user-images.githubusercontent.com/351125/53042875-ff3c6480-3465-11e9-93f0-aee27c474e32.gif" width="250" />

**Comment by elihart** [comment]
On the Epoxy side the easiest way to animate the view is to use an @ModelView and pass a prop for whether it is toggled. When you rebuild models it will call only that method on the view and the view can animate itself however it wants. Sounds like you're basically already doing that, so what else is giving you problems with Epoxy?

For MvRx, the view model state should contain the boolean values for each option declaring if it is selected or not

**Comment by bernaferrari** [comment]
lol, I have no idea, but things are working perfectly now, so thanks! Really awesome to make a reactive settings screen!

**Comment by bernaferrari** [comment]
I'm having this weird issue: https://imgur.com/CFqb0nZ

Sometimes works, sometimes doesn't. I want that animation.
Any ideas?

**Comment by elihart** [comment]
hard to say from a video, would be some bug in your source.

**Comment by bernaferrari** [comment]
That's weird. My source is (currently) really simple.

If you don't matter looking at it, this [is the fragment](https://github.com/bernaferrari/SDKMonitor/blob/master/app/src/main/java/com/bernaferrari/sdkmonitor/settings/SettingsFragment.kt) and the [ViewModel](https://github.com/bernaferrari/SDKMonitor/blob/master/app/src/main/java/com/bernaferrari/sdkmonitor/settings/SettingsRxViewModel.kt). Both together are less than 150 LOC.
