### ISSUE TITLE
Improve the document

### ISSUE THREAD

**Issue by MarcSteven** [airbnb/MvRx#202]
Glad to find your sharing ,but for developers choosing a framework is not a good case especially when you chose the library owned bad documents to tell the more developer to use it, as a developer why use the library ?Just wanna save times and avoid reinventing wheels ,but when I read the project folder ,cannot find the folder about the project .
Perhaps more details is necessary .
I found it's invisible   about the content of **Unit test**?
Perhaps it's not a good question ,but for me there is not a good documentation to use it .Thank for your sharing.

**Comment by gpeal** [comment]
@MarcSteven [The Wiki](https://github.com/airbnb/MvRx/wiki) is home to the documentation.
