### ISSUE TITLE
Is that expected behavior of uniqueOnly = true?

### ISSUE THREAD

**Issue by alexbchr** [airbnb/MvRx#204]
In my app, let's say I have a Fragment with a simple MvRxState, containing one boolean property `showError`, which by default is false.

In my fragment, in my `onCreate`, I register to this property using this code: 
```kotlin
mViewModel.selectSubscribe(this, MainState::showError, uniqueOnly = true) {
    if (it) {
        context?.let { context -> Toast.makeText(context, R.string.error, Toast.LENGTH_SHORT).show() }
    }
}
```

The behavior is as expected when I first set `showError = true`. The error toast is displayed and it is not shown again if I press the home button and come back to the app. However, if I rotate the screen, the `selectSubscribe` call is registered again and called again, with the same `true` value.

However, according to the `uniqueOnly` parameter documentation in `MvRxView`:
```
If true, when this MvRxView goes from a stopped to start lifecycle a state value will only 
be emitted if the state changed. This is useful for transient views that should only be 
shown once (toasts, poptarts), or logging. Most other views should use false, as when 
a view is destroyed and recreated the previous state is necessary to recreate the view.
```
If I understand the documentation correctly, the expected behavior when I rotate the screen should be that the `selectSubscribe` callback is not called again, since it is a "stopped to start lifecycle" and that the property's value didn't change.

Can you explain how exactly I should use this to get the expected behavior?

**Comment by BenSchwab** [comment]
Hi @alexbchr! @gpeal and I discussed this and it does seem like a bug based on the documentation and our intention with `uniqueOnly` We do hope to support the destroy/recreate lifecycle case, but it is a bit tricky. I will work on a fix.

In the meantime, you can model whether or not the toast has been shown in your State, or you can have the fragment/view maintain the knowledge locally with saved instance state.

Neither is particularly pretty, which is way we will work on making this work properly with the code you have above.


For anyone interested, my thought of how to fix is:
1) Give MvRxView's an id which is persisted across rotation
2) Have view models track last delivered states for a given id
3) leverage the existing uniqueOnly logic.
