### ISSUE TITLE
Releases on GitHub and Maven Central

### ISSUE THREAD

**Issue by MatushkaRossiya** [airbnb/MvRx#217]
Based on repo activity and changelog file, it seems that there should be versions 0.8.0 and 1.0.0 released, but there are none, either on GitHub's releases page, nor on Maven Central (the newest version of MvRx on both of these places is still 0.7.2). Is it intentional?

**Comment by gpeal** [comment]
@MatushkaRossiya 1.0.0 is out but we haven't officially announced it yet. It will be coupled with a blog post very soon.
