### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by jshvarts** [airbnb/MvRx#218]
Are releases being tagged? The last 2 versions were included in `CHANGELOG.md` but have not been tagged and do not show up under Releases tab on Github. 
`README.md` still mentions dependency v0.7.2.

**Comment by gpeal** [comment]
Done :) 
https://medium.com/@gpeal/announcing-mvrx-1-0-4925e06d0b56
https://github.com/airbnb/MvRx/releases/tag/v1.0.0
