### ISSUE TITLE
Typo in Wiki: MvRxStateFactory should be MvRxViewModelFactory

### ISSUE THREAD

**Issue by gdingenen** [airbnb/MvRx#220]
In the View Model Creation part of the Wiki, https://github.com/airbnb/MvRx/wiki#view-model-creation , is a typo.

> If your ViewModel requires external dependencies, or any constructor arguments besides initial state, have the ViewModel's companion object implement **MvRxStateFactory**:

I think MvRxStateFactory should be MvRxViewModelFactory.

**Comment by BenSchwab** [comment]
Thanks, updated.
