### ISSUE TITLE
Parent Fragment ViewModel

### ISSUE THREAD

**Issue by LimeByte** [airbnb/MvRx#227]
What is the best way to get the view model for the parent fragment?
Would prefer to not scope it to the activity.

I did try to create my own extension function based on `fragmentViewModel` but `lifecycleAwareLazy`, `MvRxViewModelProvider` and a few others are private.

**Comment by gpeal** [comment]
@BenSchwab This is something I've been thinking about as well. Thoughts?

**Comment by tasomaniac** [comment]
New navigation library introduced navigation graph scoped ViewModels. Some details here https://developer.android.com/jetpack/androidx/releases/navigation#2.1.0-alpha04

It would be super good to have support in MvRx. It basically allows you to have ViewModel scoped through your whole flow of child fragments.

**Comment by gpeal** [comment]
@tasomaniac I agree! I needed something similar recently.
Any takers @tasomaniac @BenSchwab @elihart @rossbacher @hellohuanlin?

**Comment by elihart** [comment]
This isn't a use case we've needed so far at Airbnb, so not a high priority for us, but it would be really cool for community support!

**Comment by IVIanuu** [comment]
What about targetFragmentViewModel()?

**Comment by gpeal** [comment]
@IVIanuu I hadn't considered this but I feel like it would be fairly simple. Have you had a need for this in practice?

**Comment by IVIanuu** [comment]
@gpeal Not really but maybe for cases where you start a fragment to get a result back.
