### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by mradzinski** [airbnb/MvRx#237]
Hi guys! I think this: https://github.com/airbnb/MvRx/wiki/Advanced-Concepts#dependent-requests is kind of outdated. It makes reference to `onSubscribe`, which I'm not entirely sure if its an internal Airbnb method or an old method which got replaced by `subscribe` and `asyncSubscribe`.

Let me know, I can PR changes if needed

**Comment by gpeal** [comment]
Thank you, I have updated it to:
```
init {
    asyncSubscribe(MyState::request1), onSuccess = {
        fetchRequest2()
    })
}
```
