### ISSUE TITLE
SavedStateHandle support?

### ISSUE THREAD

**Issue by atonamy** [airbnb/MvRx#238]
Google recently introduce [SavedStateHandle](https://developer.android.com/reference/androidx/lifecycle/SavedStateHandle) which you can use for ViewModel to keep your state after app get killed by Android.
I know McRx has `@PersistState` does it use SavedStateHandle under the hood?

**Comment by BenSchwab** [comment]
We do not currently use SavedStateHandle, but I do think it makes sense to migrate to Jetpack version.

**Comment by elihart** [comment]
Michelle Wong is going to start working on this for us

**Comment by elihart** [comment]
Done with https://github.com/airbnb/MvRx/pull/254
