### ISSUE TITLE
Passing ViewModel directly to DataBinding layout (or as epoxy model property) for event handling

### ISSUE THREAD

**Issue by idrisadetunmbi** [airbnb/MvRx#239]
The docs advises setting UI event listeners from the fragment and calling the fragment ViewModel when necessary, but I was wondering if there is an issue with making the ViewModel an epoxy model property and handling events directly through its methods.

```
...
<EditText onTextChanged="@{viewModel::handleTextChange}" />
...
<layout>
   <data>
       <variable name="viewModel" type="ViewModel" />
   </data>
</layout>
```

The other thing is if it makes sense to make a ViewModel an epoxy model property, could the ViewModel (state) properties be used in the model to bind data?

**Comment by gpeal** [comment]
@idrisadetunmbi I think it would make more sense to pass the state as an epoxy property rather than the ViewModel.

**Comment by idrisadetunmbi** [comment]
Yes, I eventually realized that at some point. Thanks for confirming it. How about the first part of the question - passing the `ViewModel` as a property and handling events directly through its methods?

**Comment by gpeal** [comment]
@idrisadetunmbi I'm currently experimenting with subscribing to ViewModels directly in views [here](https://github.com/airbnb/MvRx/pull/246) which I think would be the ideal solution for this.

**Comment by tasomaniac** [comment]
This is exactly how we use: 

```
<EditText onTextChanged="@{viewModel::handleTextChange}" />
```

**Comment by gpeal** [comment]
@idrisadetunmbi @tasomaniac Is more work required here?

**Comment by idrisadetunmbi** [comment]
Not really @gpeal; the PR referenced in your previous comment does not directly address the question (databinding layout vs custom views). But I don't think there is an issue with that approach as I specified in the question.

Closing this now, thanks.
