### ISSUE TITLE
MvRxTestRule does not guarantee test passing in ViewModels and View Tests

### ISSUE THREAD

**Issue by xMickeymikex** [airbnb/MvRx#240]
Hello,

I am using MvRx version 1.0.1 and i am having troubles with test stability.

Test Class:
```
@get:Rule val mvrxRule = MvRxTestRule()

private val state = SomeState(someData)
private val viewModel = SomeViewModel(state)

@Test
    fun onLoadingFailed_setsStateToFail() {
        val error = Throwable()

        viewModel.onLoadingFailed(error)

        withState(viewModel) { state ->
            state.loadingState shouldEqual Fail(error)
        }
    }
```

ViewModelClass:
```
class SomeViewModel(state: SomeState):BaseMvRxViewModel<SomeState>(state, BuildConfig.DEBUG) {
fun onLoadingFailed(error: Throwable) {
        setState {
            copy(loadingState = Fail(error))
        }
    }
}
```

This test occassionally fails when it is run grouped with other tests, however if run individually it does not fail. There are no other conditions in test class that could potentially cause trouble.

The same problem i had with testing ViewSubscriptions to ViewModelClass

ViewSubscription:
```
    viewModel.selectSubscribe(SomeState::loadingState) {
            when (it) {
                is Fail -> onError(it.error)
                is Success -> showSuccess()
            }
    }

  private fun onError(error: Throwable) {
        errorToast.show(error)
    }
}
```

TestClass:
```
    @get:Rule val mvRxRule = MvRxTestRule()
    .
    .
    .

    @Test
    fun loadingFail_showsError() {
        val error = Throwable()

        viewModel.onLoadingFailed(error)

        verify(errorToast).show(error)
    }

```

Tricky thing is that if i add `Thread.sleep(500)` before validation all of these tests pass so i guess there might be a bug in your Rule that does not lock every aspect to the main thread.
Maybe a solution would be to add a function to MvRxRulw to executeAllPendingStateUpdates synchronously.
 I hope you can fix that soon.

**Comment by xMickeymikex** [comment]
It might be connected to Async<*> interface but it's just a wild guess. Any feedback? :)

**Comment by BenSchwab** [comment]
@xMickeymikex Would you be able to create a sample project with multiple tests that fail when run together? It would be very helpful for us to debug this.

**Comment by xMickeymikex** [comment]
Well, I can try, but It might not be that easy. It it happening in the current project I'm working on but i cannot share the code. I'll try to set up the environment so it mimics the project's one but from what I'm seeing we are not doing anything special than just simple Activity with BaseMvRxFragment and ViewModel.

**Comment by xMickeymikex** [comment]
@BenSchwab https://github.com/xMickeymikex/mvrx-test-app there you go ;)

**Comment by BenSchwab** [comment]
@xMickeymikex At least for the sample project you sent me the issue is the creation of the view model as a property of the test class. These properties will initialized before the MvRx rule is applied. This means the view model will not be using immediate schedulers.

I would recommend recreating the view model, activity and state in setUp.

Let me know if this is also the issue in your main project!

**Comment by xMickeymikex** [comment]
Tricky, didn't think about it, and yes, it is the issue in my main project :) I tried to mirror it as good as I could!
 I'll message you back after I make these changes to a project :)

**Comment by xMickeymikex** [comment]
@BenSchwab It was the issue, thanks for reply and help! :)
