### ISSUE TITLE
When does invalidate doesn't get called even on state change?

### ISSUE THREAD

**Issue by kalyandechiraju** [airbnb/MvRx#243]
I can see the state change logs from my view model but invalidate is not getting called in the view.

```
override fun invalidate() {
		recyclerView.requestModelBuild()
	}
```

**Comment by kalyandechiraju** [comment]
Figured out the issue. It is due to the fact that I injected the viewmodel using dagger instead of provided Viewmodel factory.

Able to proceed as mentioned here: https://github.com/airbnb/MvRx/issues/69 by injecting my viewmodelProvider Factory into the activity and using it to create the viewmodel. I had to use dagger for injecting initial state as well.

Would be nice if we can have a built-in way to achieve this.

**Comment by RomanByakov** [comment]
Be attentive there are different ways for provide viewModel (fragmentViewModel,parentFragmentViewModel etc). It might be different instance of viewModel in others fragments
