### ISSUE TITLE
Usage in BottomSheetDialogFragment

### ISSUE THREAD

**Issue by zirkler** [airbnb/MvRx#257]
Hello,

first of all thanks for MvRx, it makes Android Development a pleasure, especially using it together with Epoxy is a very smooth development experience.

Right now I am facing the following problem: 
I want to use MvRx (or to more precise, I want to use `fragmentViewModel()` and `activityViewModel()`) in a `BottomSheetDialogFragment` the same way as I use it in a regular Fragment, which means I have to extend the BaseMvRxFragment class like the following:

```
class ExampleBottomSheetDialogFragment: BottomSheetDialogFragment(), BaseMvRxFragment() {
    override fun invalidate() { }
}
```

Unfortunately, this is not possible as the compiler now complains: "Only one class may appear in a supertype list".

Any ideas on this?

Thanks

**Comment by tasomaniac** [comment]
What about implementing `MvRxView`? That's just an interface and your `ExampleBottomSheetDialogFragment` can implement that.

**Comment by zirkler** [comment]
Thanks, that works for me. I created a abstract class called `BaseMvRxBottomSheetDialogFragment` which which contains the exactly same functionality as the `BaseMvRxFragment`. In my `BottomSheetDialogFragment` I then subclass the `BaseMvRxBottomSheetDialogFragment`.

**Comment by mateohervas** [comment]
@zirkler what does your BaseMvRxBottomSheetDialogFragment class look like? I am trying to work with a BottomSheetDialogFragment and MvRx but can't seem to find a way!

**Comment by zirkler** [comment]
Unfortunately I do not have access to to codebase anymore, but if I recall correctly, the BaseMvRxBottomSheetDialogFragment was simply implementing MvRxView and calling the epoxy controller to re-build it's models on `invalidate()`.

**Comment by THEAccess** [comment]
@mateohervas Here's how I did it about 9 months ago: https://gist.github.com/THEAccess/1fc7a3138aac1f4a629f27a71b2e3b68 
This was before Mavericks 2.0.0 so I don't know if it's still compatible but It worked perfectly fine with previous versions of MvRx
