### ISSUE TITLE
How can I change the view after the state is initialized?

### ISSUE THREAD

**Issue by 1van** [airbnb/MvRx#261]
Hello! :smile: 

I want to change the view multiple times, 
but "XXX was mutated. State classes should be immutable."

thank you.

**Comment by elihart** [comment]
You must call `setState` from the ViewModel. The data class should be copied and a new version made.

see the wiki
https://github.com/airbnb/MvRx/wiki#core-concepts
https://github.com/airbnb/MvRx/wiki#updating-state

**Comment by 1van** [comment]
@elihart 
I did call `setState` or `execute` from the ViewModel, but it’s not work when I use epoxy + pagging support.

**Comment by 1van** [comment]
Thank you for your answer!~ 

    implementation 'com.airbnb.android:mvrx:0.7.2'
    implementation 'com.airbnb.android:epoxy:2.19.0'
    implementation 'com.airbnb.android:epoxy-paging:2.19.0'

```kotlin
data class LandMainState(
    val historyItemData: Async<List<LandMainAlbum>> = Uninitialized,
    ...
    val albumAllItemData: Async<PagedList<Pair<Album, Album>>> = Uninitialized
) : MvRxState
```
```kotlin
class LandMainViewModel(state: LandMainState) : MvRxViewModel<LandMainState>(state) {
    fun loadHistoryCards() {
        LandMainLocalDataSource.getHistoryCars()
            .subscribeOn(Schedulers.io())
            .execute { copy(historyItemData = it) }
    }
}
```
```kotlin
viewModel.asyncSubscribe(this, LandMainViewModel::albumAllItemData) {
    rxController.submitList(it)
}
```
I call `submitList` in the Activity#onCreate(), then i want to call `loadHistoryCards` in the Activity#onResume(). Crash happened..

**Comment by 1van** [comment]
I got it, `PagedList` cannot be used in State.
