### ISSUE TITLE
Separate PersistState support into separate dependency

### ISSUE THREAD

**Issue by tasomaniac** [airbnb/MvRx#274]
I've realized that MvRx is doing some reflection but they are all for debug checks and persist state. 

I was thinking those can be put into separate dependencies so that the clients would not have to depend on `kotlin-reflect` on production (considerably big dependency).

**Comment by kaushalyap** [comment]
@gpeal Any plan to get rid of `kotlin-reflect`?

**Comment by gpeal** [comment]
@kaushalyap https://github.com/airbnb/MvRx/pull/334 😄
