### ISSUE TITLE
Add sample for MvRx usage with Dagger

### ISSUE THREAD

**Issue by haroldadmin** [airbnb/MvRx#278]
I've recently spent some time integrating Dagger with an app using MvRx, and I was thinking it would could be useful for people if this repository contained an official sample for this too. A sample application using MvRx with Dagger and AssistedInject.

I could refactor an existing sample app in this repo to use Dagger, or maybe create an entirely new one. Thoughts?

**Comment by tomislavhofman** [comment]
If somebody is looking for a working example @chrisbanes has incorporated both Dagger2 and MvRx into his app **_Tivi_** which can be found here
https://github.com/chrisbanes/tivi

App is split into modules ( libraries ) so you also get a benefit of learning how to work with modular apps.

**Comment by haroldadmin** [comment]
I've actually developed a small news listing app to demonstrate MvRx with Dagger and AssistedInject. I'll clean up the code and make a Pull Request for it in a few days.
