### ISSUE TITLE
Crash using MvRx with Flowable.combineLatest 

### ISSUE THREAD

**Issue by VGJohn** [airbnb/MvRx#280]
Hi,

I'm having an issue using Flowable.combineLatest() and MvRx that results in a crash. I believe the crash results from the fact that combineLatest caches the last items that are output from the combined streams. 

For example, say I'm combining a Flowable for a Dog object and another Flowable for a DogCollar object. But inside the BiFunction I'm adding some additional data to the Dog object like it's Owner details which I'm getting from another source. Both Flowables will output a Dog and DogCollar object which combineLatest then caches as I understand it.

The issue arises in the BiFunction since I'm modifying the cached Dog object with some additional data insides its model (adding the Owner details). The Dog object itself will be the same but the Owner details within the Dog object may have updated. This results in MvRx crashing saying that I've changed the immutable state which is technically correct I believe.

I found a way to avoid this by just making a copy (Kotlin data class copy) of the Dog object before updating the Owner details inside. This way MvRx considers it a new object when computing its diff when it is output from the combineLatest stream.

What I would like to know is if I'm approaching this correctly? And if so, is my solution by using Kotlin's data class copy function correct? Not sure if I'm purposefully triggering another MvRx diff that could be avoided possibly? 

Cheers,
John

**Comment by elihart** [comment]
It sounds like your approach to copying the model should be correct, but can you share the before and after code?

**Comment by VGJohn** [comment]
@elihart Sorry for not getting back sooner on this, I forked the repo and updated the todomvrx sample app with minimal changes to reproduce the crash. https://github.com/VGJohn/MvRx

Steps to reproduce: 
1. Deploy updated sample todomvrx app
2. Click "plus" fab button to create a new todo
3. Enter some title for the todo
4. Click "check" fab button to save the todo
5. Wait two seconds for the artificial delay to finish... crashes because of immutable state change within the BiFunction of the combineLatest

**Comment by gpeal** [comment]
@VGJohn Feel free to reopen this if it is still an issue. Your fork is 404ing for me.
