### ISSUE TITLE
Property Getters in State

### ISSUE THREAD

**Issue by LimeByte** [airbnb/MvRx#281]
What are your thoughts on property getters on the state?

Some examples:

``` kotlin
val isLoading: Boolean
    get() = data is Incomplete
```

``` kotlin
val canSubmit: Boolean
    get() = !isPerformingAction && error == null && !note.isNullOrEmpty() && deliveryDate != null && hasOneOrMoreItems
```

**Comment by elihart** [comment]
This is a fine pattern - just make sure that it depends only on primary constructor properties.

We use this approach commonly ourselves.

**Comment by gpeal** [comment]
@LimeByte Same, super useful pattern, we use this a ton at Tonal too.
