### ISSUE TITLE
`NetworkBoundResource` and `Async`

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#294]
Are you familiar with `NetworkBoundResource`?
It's Google's concept https://github.com/android/architecture-components-samples/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/NetworkBoundResource.kt

I'm wondering if anyone has implemented it with `RxJava`, `MvRx` and `Async` class. In case, feel free to share your code. 😊

**Comment by gpeal** [comment]
@qbait The thought is that that sort of logic would be one level down the stack, say in a repository in which case it would be out of scope for MvRx as it stands today. Thoughts?

cc @elihart @BenSchwab
