### ISSUE TITLE
Wrong comment in real mvrx state store 

### ISSUE THREAD

**Issue by digitalbuddha** [airbnb/MvRx#296]
https://github.com/airbnb/MvRx/blob/8375363d29cdab3561b5259118c2c2e4190cc562/mvrx/src/main/kotlin/com/airbnb/mvrx/RealMvRxStateStore.kt#L24 the comment refers to an observer while the next line is a disposable

**Comment by elihart** [comment]
Thanks for catching this. will update it as some point (or anyone else is welcome to put up a PR!)

**Comment by gpeal** [comment]
This will be deprecated by #347

**Comment by gpeal** [comment]
Fixed bt #347
