### ISSUE TITLE
How to share data between fragments with multiple ViewModels?

### ISSUE THREAD

**Issue by JakeWoki** [airbnb/MvRx#297]
communicating between fragments using different ViewModel

**Comment by sandys** [comment]
i was googling some time earlier for a similar question and this thing popped up
https://twitter.com/gpeal8/status/1163819677220405249

> all fragments that use the same viewmodel must come from the same activity" ?
> 
> Yes, the latter is definitely true. The whole app doesn't have to be one activity but collections of related fragments always are.

**Comment by gpeal** [comment]
This can help as well
https://github.com/airbnb/MvRx/pull/287

I'm going to close this for now since it's not directly actionable.
