### ISSUE TITLE
Is selectSubscribe still coalesced?

### ISSUE THREAD

**Issue by mradzinski** [airbnb/MvRx#298]
Hi guys,

I thought state coalescing was removed a few ago, but today I've noticed that `selectSubscribe` seems to behave like if the state was still being"coalesced". For example, I have a few `selectSubscribe`s (with and without `uniqueOnly`) which unless I'm mistaken seem to be called only if upon states the "selected" property changes its previous value.

As a side note, digging a bit into the code I saw that `selectSubscribeInternal` has a `distinctUntilChanged()` chained, so this might be the reason why.

If this is intentional then it might be worth a mention in the wiki.

**Comment by elihart** [comment]
This is intended. From the kdoc of that function
```
A callback that will be triggered every time the selected field has an updated value, as determined by the <code>equals</code> method of {@link T}.
```

**Comment by gpeal** [comment]
@mradzinski It is not coalesced in the sense that if multiple state properties are handled in one frame, you will get a subscription callback for each one. However, the `distinctUntilChanged()` serves to prevent your selectSubscribe from getting called with _other_ state properties change.

Let me know if there is something else needed for this issue. I'm going to close it for now though.
