### ISSUE TITLE
Write espresso tests for todomvrx

### ISSUE THREAD

**Issue by gpeal** [airbnb/MvRx#30]

**Comment by herrbert74** [comment]
Why was this closed? Is this possible at all? Having little experience with both Espresso and MvRx, I'm struggling to write my first Espresso test after switching to MvRx. FragmentScenario seems the wrong approach as the Activity needs to be MvRx specific. I couldn't make ActivityTestRule to work so far. Anybody could provide a basic example?

**Comment by elihart** [comment]
With the latest release https://github.com/airbnb/MvRx/pull/311 it is not necessary to have a mvrx specific activity, so FragmentScenario should work fine.

You should be able to use espresso fine with mvrx - it's just a little tedious to set states which is being improved with https://github.com/airbnb/MvRx/pull/282

**Comment by herrbert74** [comment]
Thanks, that's useful. I updated MvRx, but after all I managed to write tests with ActivityTestRule. We switched to Navigation components, modularization and Dagger at the same time, which made it a bit harder, that's all.

**Comment by vishalkumarsinghvi** [comment]
@herrbert74 Can you please share your todomvrx test cases, I am looking for mvrx test case & I am not getting it..
