### ISSUE TITLE
RealMvRxStateStore not getting disposed

### ISSUE THREAD

**Issue by xMickeymikex** [airbnb/MvRx#301]
Hello ;) 

We have recently investigated our thread pool and we caught something that was very confusing for us. Our RxNewThreadPool was increasing all the time. We do not use rx newThreads in our app so we knew that the problem lies in libraries. 

```
class RealMvRxStateStore<S : Any>(initialState: S) : MvRxStateStore<S> {
    private val disposables = CompositeDisposable()
    private val flushQueueSubject = BehaviorSubject.create<Unit>()
    ...

    init {

        flushQueueSubject.observeOn(Schedulers.newThread())
            // We don't want race conditions with setting the state on multiple background threads
            // simultaneously in which two state reducers get the same initial state to reduce.
            .subscribe({ _ -> flushQueues() }, ::handleError)
            // Ensure that state updates don't get processes after dispose.
            .registerDisposable()
    }
    ...
    override fun isDisposed() = disposables.isDisposed

    // Never called anywhere!
    override fun dispose() {
        disposables.dispose()
    }

    private fun Disposable.registerDisposable(): Disposable {
        disposables.add(this)
        return this
    }
}
```

This code would be pefectly fine, BUT dispose is never called on StateStore and this leads to infinite threads creation which then leads to app crash.

We managed to make it work just by creating RealMvRxStateStore manually in ViewModel and disposing it in `onCleared()` method. This end up with perfectly fine thread management.

I'm pretty sure this is a bug and should be fixed :)

**Comment by elihart** [comment]
Thanks for sharing. I noticed this recently too and included a fix in my in progress PR - https://github.com/airbnb/MvRx/pull/282/files#diff-d6da0afe1caeee8562010718cd2c4257R93

I didn't realize this was causing the thread to stick around, but I guess that makes sense. We could make this change as a one-off PR since mine will not likely be merged for a while still

**Comment by xMickeymikex** [comment]
If you were able to make this small hotfix and publish to maven i would be very pleased :)

**Comment by xMickeymikex** [comment]
Nevermind @elihart ;) https://github.com/airbnb/MvRx/pull/302 there you go
