### ISSUE TITLE
MvRx-Dagger Module

### ISSUE THREAD

**Issue by BenSchwab** [airbnb/MvRx#314]
Want to track ideas/interest for a dedicated MvRx-Dagger module.

We would formalize some ideas introduced in https://github.com/airbnb/MvRx/pull/307 with some additions:

1)
An annotation processor would generate:

```
 @AssistedInject.Factory
    interface Factory : AssistedViewModelFactory<HelloViewModel, HelloState> {
        override fun create(state: HelloState): HelloViewModel
    }
```
By looking for view models with `@AssistedInject` annotations

2) A  `DaggerMvRxViewModelFactory` automatically returns a ViewModel instance from the assisted inject module.

3) Maybe generate

```
@AssistedModule
@Module(includes = [AssistedInject_AppModule::class])
interface AppModule {

    @Binds
    @IntoMap
    @ViewModelKey(HelloViewModel::class)
    fun helloViewModelFactory(factory: HelloViewModel.Factory): AssistedViewModelFactory<*, *>

} 
```

(Need to verify how Assisted inject handles multi-round annotation processing).

The main goal is to reduce any boilerplate to setting up DI with MvRx.  It seems to me that annotating a view model with `AssistedInject` and choosing what component to install the dagger module which knows how to create the view model are the only parts of the injection process that a user should need to specify.

This would be published as a `mvrx-dagger` artifact with a dependency on `AssistedInject` and it's own annotation processor.

**Comment by elihart** [comment]
I'm in favor of generating as much as possible with an annotation processor :D (with incremental support of course).

It may be worth figuring out how we may want to support injecting nested view models first before committing to an architecture for this. Ideally the nested view models could be injected easily with this system too.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/MvRx/pull/307
