### ISSUE TITLE
Dependent subscriptions not disposed automatically

### ISSUE THREAD

**Issue by jankowskib** [airbnb/MvRx#316]
Hello, I have observable inside asyncSubscribe i.e
```
  fun observeStatus(id: Integer): Observable<Status> { ... }

  init {
        asyncSubscribe(RadioState::stationRequest) { station ->
            observeStatus(station.id).execute { copy(statusRequest = it)) }
        }
    }
```
The problem is when `stationRequest` changes, the subscription for `observeStatus` is not disposed and I'm getting status for both old and new `station.id` when `observeStatus` emits an item. I tried idea with keeping Disposable and disposing it manually inside view model, but not really happy from this solution. It'd nice if there was an operator like switchSubscribe which will be disposing given observable/single when state's property changes.
What could be better solution for that problem?

**Comment by elihart** [comment]
Right now you have to hold a reference to that disposable and dispose it manually when you don't want its result any longer.

I have some ideas on how to improve this that I'll try to get around to sharing in a PR soon

**Comment by jankowskib** [comment]
Thank you for your response. Looking forward for the PR :)
