### ISSUE TITLE
add extension function for coroutines Flow<T>

### ISSUE THREAD

**Issue by atonamy** [airbnb/MvRx#319]
Can we add in new version `execute` extension function for coroutines [Flow](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/) into `BaseMvRxViewModel`?

So rough implementation could be something like this:

```
inline fun <T> Flow<T>.execute(crossinline stateReducer: S.(Async<T>) -> S) =
        GlobalScope.launch {
            setState {
                stateReducer(this, Loading())
            }
            catch {
                setState {
                    stateReducer(this, Fail(it))
                }
            }
            collect {
                setState {
                    stateReducer(this, Success(it))
                }
            }
        }
```

**Comment by elihart** [comment]
This should not be using GlobalScope. The scope should be passed to the viewmodel as a parameter, which you can do in your own base view model.

It doesn't make sense for us to provide extension functions like this until we have a comprehensive solution to providing a scope by default in mvrx - but we need to take into account testability and customization API's so it isn't too simple. It's something that we should hope to do fairly soon though.

We can also make an extension like this for `Deferred<T>`

**Comment by atonamy** [comment]
@elihart 
Can we define scope something like this?
`private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())` and `use scope.launch { ... }` instead?
then
```
 override fun onCleared() {
        super.onCleared()
        scope.coroutineContext.cancelChildren()
    }
```

**Comment by elihart** [comment]
sure, that would work. I prefer to remove the boilerplate of `scope.X` and so I make it an interface - but you can do whatever you want in your own view model.

**Comment by gpeal** [comment]
@atonamy MvRx (Mavericks) 2.0 is completely rewritten with Coroutines so it has all of this out of the box. 2.0.0-alpha7 is out and it's stable enough for use in production (we are using in in production at Tonal)
