### ISSUE TITLE
It reloads when you switch fragments

### ISSUE THREAD

**Issue by RDSunhy** [airbnb/MvRx#322]
I use navigation to jump the fragment, and when I go back to the previous fragment it reloads the init call.
This is probably because of navigation. I would like to ask if you have any good solutions?

**Comment by gpeal** [comment]
@RDSunhy init in your ViewModel? That shouldn't happen. Please attach a sample project that reproduces this.

**Comment by RDSunhy** [comment]
I found the problem.
EpoxyRecyclerView externally added NestedScrollView, the list returns to the top whenever I toggle fragments.BottomNavigationView is also used in my project.I think this may not be MvRx's problem.
I refer to your product (Airbnb app), I think everything is great!
I would like to ask you how do you handle switching between fragments?Can you give me some ideas?I'd like to refer to your design ideas.

**Comment by gpeal** [comment]
@RDSunhy MvRx has no opinions on navigation. You can do whatever you would like.
I have seem navigation sealed classes that you can subscribe to with uniqueOnly() which seems to work well.
