### ISSUE TITLE
Using MvRx and Epoxy for the view that is not a typical list?

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#325]
Let's say, I need to implement a login screen like:
<img width="208" alt="Screenshot 2019-11-27 at 11 47 04" src="https://user-images.githubusercontent.com/2264901/69717115-be1b6400-110b-11ea-915d-b2678e8181c3.png">

Is there a way to create a non-scrollable fragment with views aligned to the bottom like that using `Epoxy` / `RecyclerView`? Or is it overkill and is it better to use normal `ConstraintLayout` for that?

**Comment by elihart** [comment]
I wouldn't use Epoxy, use a normal layout. You can use MvRx fine though, not sure why this is a MvRx question - you can use databinding or whatever you want
