### ISSUE TITLE
Creating view actions not dependent on state

### ISSUE THREAD

**Issue by xMickeymikex** [airbnb/MvRx#329]
Hello,

I have been working with MvRx for almost a year now and I must say i'm really satisfied of how it works and simplifies view/logic isolation ;).

However I am missing one thing in this concept, which is what I call "ViewActions". It is an anonymous action on the view eg. `showToast`, `showPopup` which I think should not be included in a `ViewState` as It could very easy become very overloaded State but should be possible for `ViewModel` to invoke. I couldn't find it in documentation and that's why i decided to write this post :).

My concept extends ViewModel functionality with a function called `makeAction` which could be a stream for a `View` to observe and react on it. Yes, you could create this functionality using state and "posting" these actions into state, but it is more like a hack than a solution to a given problem.

Give me your thoughts about it ;)

**Comment by renaudcerrato** [comment]
Have a look at [this post](https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150).

**Comment by xMickeymikex** [comment]
@renaudcerrato Well yes, this is something you could do, and this is what i would like to achieve in a more generic way, so that you have an architecture over it to protect from uncontrollable behaviour. Creating many observable/livedata streams inside view model and subscribing to them in a view could lead to potential RC. When you wrap it in a single subscription like `setState` and `getState` the problem is solved and debugging is way easier.

**Comment by renaudcerrato** [comment]
I'm usually using that `SingleEvent` pattern, and my MvRx state holds a single `events` stream:

```
data class MyState(..., val events: SingleEvent<*>)
```

**Comment by xMickeymikex** [comment]
Exactly, that was what i called a hack solution ;).  For me state is not the valid place for one-time events, as they are not really a "part" of state and it gives a redundant object into a state, making it less performant every time you copy it for a new state. 
Isolated solution could lead to better performance and less confusion in terms of reading/debugging the state.

**Comment by renaudcerrato** [comment]
If those events are not part of your state, why putting them into? Use another channel ? An event bus for example?

**Comment by xMickeymikex** [comment]
EventBus is just a tool to achieve it(what's the difference between EventBus and "EventStream"). I'm talking about concept of short-time actions handling by MvRx, as it is not included now, not about technical implementation of it.

**Comment by renaudcerrato** [comment]
MvRx is all about view state: I'm not sure I'd like MvRx to go outside that scope. If the user actions doesn't modify your state, that shouldn't go through your view model : do it in directly your view instead. For example: copying some text to the clipboard and showing a confirmation toast.

**Comment by xMickeymikex** [comment]
It's not always that easy. Many times you have user interaction which leads to some business logic processing and then completes with something like `Toast` or `AlertDialog`. Doing this directly inside view breaks every Architecture pattern i know :P And Toast or dialog is something transitory and it shouldn't be part of a state.

**Comment by elihart** [comment]
Generally we have used `selectSubscribe` with `uniqueOnly` in the Fragment to decide when to show transitory things like toasts. Any reason that doesn't work for you?

**Comment by xMickeymikex** [comment]
@elihart it will do for sure, i decided to write this post, because i think it could be a part of a `ViewModel` itself as these transitory things are not really a part of a state - which I understand as a "static" view content. 
Creating this kind of "action" stream would be a nice addition to MvRx concept making it way more flexible, developer-friendly and cleaner(from transitory-boilerplate in state) :).

**Comment by elihart** [comment]
Do you have a suggested API for what this support would look like?

**Comment by xMickeymikex** [comment]
I'll try to figure it out in few days and come back with an answer ;).

**Comment by gpeal** [comment]
@xMickeymikex Any ideas or can we close this?

**Comment by xMickeymikex** [comment]
@gpeal  we can close, unique only is fair enough ;)
