### ISSUE TITLE
MvRxLauncher: ClassNotFoundException on DexPathList

### ISSUE THREAD

**Issue by carlosmuvi** [airbnb/MvRx#335]
First of all, thanks for making public and maintaining MvRx, and now MvRxLauncher! 

Trying to launch `MvRxLauncherActivity` throws missing class exceptions on the dex path.

The missing class varies after rebuilding. 

Sample stacktrace:

```
java.lang.ClassNotFoundException: Didn't find class "com.jumio.nv.custom.NetverifyCustomFaceScanPresenter$a" on path: DexPathList[[zip file "/data/app/appPackage-zHYXyaLpJSqh2m9NvQzKRw==/base.apk"],nativeLibraryDirectories=[/data/app/appPackage-zHYXyaLpJSqh2m9NvQzKRw==/lib/arm64, /data/app/appPackage-zHYXyaLpJSqh2m9NvQzKRw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
```

For more reference, this was tested on a multi-module project with a structure like the following:

:app -> :featureA

- :app Depends on `mvrx` and `mvrx-launcher`
- There's just one MvRxFragment, that lives in :featureA.

**Comment by elihart** [comment]
Thanks for sharing this. Can you provide more of the stacktrace? Where is this class being accessed from?

How are you  launching the `MvRxLauncherActivity`  exactly?

**Comment by carlosmuvi** [comment]
Attaching a couple of stacktraces below. This is the structure we're playing with:

```
 :app <- :featureA (`FeatureAFragment: MockableMvRxView` lives here) 
      <- :debugTools (`MvRxLauncherActivity` launched here by canonical name)
```

just :app depends on `mvrx-launcher`. We tried different configurations, but just the not found class varies. `MvRxLauncherActivity` gets launched, the loading is seen and then it crashes.

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/625017/71562697-2eefcc00-2a7c-11ea-9aed-c1a34008ac7e.png">

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/625017/71562708-3b742480-2a7c-11ea-8f1c-0935165efcb6.png">

**Comment by elihart** [comment]
Thanks for the stacktrace. I don't know why the class isn't found when it is in the dex, but it should be ok for us to add a try/catch for ClassNotFoundException when iterating through the classes. Feel free to put up a PR for that, otherwise we will get to it eventually

**Comment by carlosmuvi** [comment]
Catching potential `ClassNotFoundException` while iterating seems to be working perfectly, thanks for the suggestion! #345 includes it in your `MvRxLauncher` branch. : )

**Comment by carlosmuvi** [comment]
Closing
