### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by ursusursus** [airbnb/MvRx#336]
// Testing of Async in viewmodel constructor with synchronous schedulers

Hi, I'd like some pointers on testing.

From what I can see I can jump start the view model with intial state which is grear. However, given I call some async rx stuff in the view model constructor, and usual recommendation to have synchronous schedulers swapped in for testing, wouldnt this mean that I can never assert Async.Loading? 

(Since Loading is emitted synchronously, so is then Success, now ctor is exited, and now I can test the state observable, meaning atleast I would miss Loading)

Unless I can swap out the state store observable somehow to cache everything, so I can assert it?

**Comment by gpeal** [comment]
@ursusursus You can inject a scheduler into your constructor. Give it a default value for production (ie `Schedulers.io()`) then pass in a test scheduler for your tests.

If synchronous tests are okay, you can use the `MvRxTestRule`
https://github.com/airbnb/MvRx/wiki#testing
