### ISSUE TITLE
FetchPrevPage? The best way to load items dynamically at the top of list

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#338]
When I load items dynamically at the bottom of the list, my code looks like

```
        loadingRow {
            id("loading${state.events.size}")
            onBind { _, _, _ -> viewModel.fetchNextPage() }
        }
```

What's the best way to load items dynamically at the top of the list? 

I've tried something like, but unfortunately `onBind` is not suitable at the top of the list.
```
    override fun epoxyController() = simpleController(viewModel) { state ->

        loadingRow {
            id("loading${state.events.size}")
            onBind { _, _, _ -> viewModel.fetchPrevPage() }
        }

        state.items.forEachIndexed { index, item ->
                    eventRow { ... }
        }

        loadingRow {
            id("loading${state.events.size}")
            onBind { _, _, _ -> viewModel.fetchNextPage() }
        }
    }
```

**Comment by elihart** [comment]
What is wrong with the onBind behavior at the top of the page that you shared? Why doesn't it work, and what behavior do you want instead?

Generally if you want fine grain control your best bet is to register a scroll listener with the recyclerview (and then you can check positions with the layout manager) and you can load the previous pages whenever you want)

**Comment by qbait** [comment]
thanks @elihart . Will do that with a scroll listener.
