### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by chitra-bahadur** [airbnb/MvRx#340]
facing crash with version 2.0.0-alpha2
You must specify a viewModelConfigFactory in the MvRx object

**Comment by tomislavhofman** [comment]
You must specify viewModelConfigFactory as noted
[here](https://github.com/airbnb/MvRx/releases/tag/2.0.0-alpha1) and [here](https://github.com/airbnb/MvRx/wiki/Integrating-MvRx-In-Your-App)

> 
> Simple setup can be done from your application initialization like this:
> 
> `MvRx.viewModelConfigFactory = MvRxViewModelConfigFactory(applicationContext)`
