### ISSUE TITLE
Subscriptions are fired again when resuming using RedeliverOnStartup, regardless of the previous values.

### ISSUE THREAD

**Issue by renaudcerrato** [airbnb/MvRx#342]
Using `RedeliverOnStartup`, all subscriptions are fired again when the activity/fragment is resumed, regardless of the previous values. That's a waste of CPU if the state wasn't updated in background.

I'd expect subscriptions to fire only if the value(s) changed, or if the activity/fragment has been re-created.

**Comment by gpeal** [comment]
@renaudcerrato use UniqueOnly if you want that behavior. This is the expected behavior for RedeliverOnStartup.

**Comment by renaudcerrato** [comment]
If I'm not wrong, `UniqueOnly` doesn't redeliver on configuration change which doesn't fulfill my expectations in order to not waste CPU : subscriptions should only fires when the value(s) change OR if the view has been destroyed and re-created. 

Updating my entire UI state after every `onResume()` is such a waste.

**Comment by gpeal** [comment]
@renaudcerrato MvRx only redelivers on start, not on resume. Is something triggering your state to change when your fragment is resumed?

**Comment by renaudcerrato** [comment]
When the activity is coming from the background (for example), onStart() is triggered again and so the subscriptions.

**Comment by gpeal** [comment]
@renaudcerrato Yes, that is correct. Your UI should be idempotent. Calling invalidate again should have close to 0 performance overhead.
