### ISSUE TITLE
Advice on how to "rewrap" Async with function parameters

### ISSUE THREAD

**Issue by ursusursus** [airbnb/MvRx#349]
Hi, I often find my self wondering how to most cleanly handle this case, where I'd best like to change T of the Async with function parameter, or somehow attach it theresomehow

`data class State(val activateAsync: Async<Unit>, ...)`

```
fun activateProduct(product: Product) {
	productRepository.activate(product.id)
		.execute {
			copy(activateAsync = it)
		}
}

```
`fun ProductRepository.activate(productId: String) : Single<Unit>`

i.e. repository returns Unit, however UI wants to react with rendering the given product id

```
fun renderState(state: State) {
	when(state.activateAsync) {
		is Success -> showToast("Product of id $???? activated successfully")
		...
	}
}
```

So the issue is we have a` Async<Unit>` whereas I'd want to have `Async<Product>`.
Obviously I know I can rewrap it into a new` Async<Product>` instance as subscriber level (but it uglyfies the `execute` function
Or maybe `productRepository.activate(product.id).map { product }`? 
Or even inside the repository function?
Maybe some factory lambdas as params of the execute function, as not to create the `Async<Unit>` instance at all?

Anyways, all options feel like a hassle. I'm sure you've encountered this. Any pointers from experience?

**Comment by gpeal** [comment]
@ursusursus usually, the signature of your repository would look more like:
`fun ProductRepository.activate(productId: String) : Single<Product>`. That would solve your problem.

`productRepository.activate(product.id).map { product }` would also work fine. Either way, I don't think this is MvRx specific so I'm going to close this issue.

**Comment by ursusursus** [comment]
Yea I'm just looking for guidance, as this comes up a lot, same as you optimize your `execute` case, thanks
