### ISSUE TITLE
Advice on how to handle transient errors re-renders

### ISSUE THREAD

**Issue by ursusursus** [airbnb/MvRx#350]
Hi,
my another grip is with transient errors, or rather their repeat rendering. Use case is a basic request

```
data class State(val activateAsync: Async<Unit>, ...)

fun activateProduct(product: Product) {
	productRepository.activate(product.id)
		.execute {
			copy(activateAsync = it)
		}
}
```

**Where UI would like to show a toast or error.**

Yes we can filter the state observable as to only show to toast once (per view lifetime), however what bothers me is going to background and back, i.e. destroying of the view, while viewmodel is still in memory. 

Which means another instance of the view (after comming back to foreground) will receive the previously cached state, which will in turn show the toast again. Same for rotations.

How should one best handle this annoying case? 

Should I just reset the activateAsync to Uninitialized right away synchronously? Probably not since stateObservable is throttled internally, correct?

Maybe reset it after a arbitrary delay since Toast doesnt have a listener?

Not use toasts? Snackbars have the same problem, but do have a dismiss listener. Dialogs, same.

**Comment by gpeal** [comment]
@ursusursus use `deliveryMode = uniqueOnly()` for something like this.
It is also acceptable to reset the error once you have shown it to the user. I'm not sure what you mean by the state observable being throttled?

Please go ahead and close this if it resolves your issue.

**Comment by ursusursus** [comment]
well, `unique` doesnt work for me over orientation changes. since youre subscribed in one of the view callbacks right? it would work if subscribed in constructor, however then the viewmodel instantiation via by activityViewModel() doesnt work

**Comment by gpeal** [comment]
@ursusursus I don't follow.
