### ISSUE TITLE
withState with return value

### ISSUE THREAD

**Issue by Glurt** [airbnb/MvRx#357]
I have a helper class in my ViewModel that gives callbacks when events occur, these callbacks want a return value. I need to access the state in these callbacks in order to provide the correct return value but I can't figure out how. 

As far as I can tell, `withState` is the only way to get the current state but as it takes `block: (state: S) -> Unit` I'm unable to return anything from it. 

Is there a specific reason for this or could this be updated to include an optional return value?

**Comment by gpeal** [comment]
@Glurt Yes, `withState` is put on the reducer queue to ensure that all `setState` reducers have been processed. Without it, people would accidentally write code like this:
```
setState { copy(foo = 5) }
withState { state ->
    // Foo is expected to be 5 but setState hasn't been processed yet so it actually has the previous value
}
```

**Comment by Glurt** [comment]
I'm not sure I follow, isn't your example possible to write now?

Would changing `withState` to something like `block: (state: S) -> R` effect the way the reducer queue works?

**Comment by gpeal** [comment]
@Glurt 
```
setState { 
    // I am run second
}
withState { state ->
    // I am run third
}
// I am run first
```

setState and withState are run asynchronously so the withState lambda can't return anything.

**Comment by Glurt** [comment]
Right I understand you now, I probably should have searched the wiki before posting this. 

Thanks for explaining it
