### ISSUE TITLE
Upgrade compile compatibility to Java 8

### ISSUE THREAD

**Issue by jpventura** [airbnb/MvRx#359]
Upgrade both source and target compatibility options to Java 8 at:

  - [x] `counter`
  - [x] `dogs`
  - [x] `sample`
  - [x] `todomvrx`

Upgrade Kotlin options to Java 8 at
  - [x] `counter`
  - [x] `dogs`
  - [x] `sample`
  - [x] `testing`
  - [x] `todomvrx`

**Comment by jpventura** [comment]
@elihart soon I will send another PR, organizing the [library dependencies into a single  `dependencies.gradle` file](https://medium.com/google-developer-experts/19-tips-for-gradle-in-android-projects-2019-edition-11af704eb06e), making easier bumping them.

I am sending small _cosmetical PRs_ before it in order to help you people in the review process.

**Comment by elihart** [comment]
Fantastic :) thanks so much for helping out

**Comment by jpventura** [comment]
@elihart well, at least I have something to do during the quarantine :smile:. Just let me know if you have any concerns about the PR #360
