### ISSUE TITLE
How to re-use Fragment with different ViewModels?

### ISSUE THREAD

**Issue by zirkler** [airbnb/MvRx#368]
Hello there,

I have an android question which occupies my mind already since a few days. Imagine you have Fragment which is supposed to be reused in multiple usecases, e.g. called "AddOrEditRecipe", this fragment can be used for creating or editing a recipe, since, you know, it is the exact same UI no matter if you create or edit.

But I want to either use a AddRecipeViewModel or EditRecipeViewModel, depending on the usecase, which is identified by a FragmentArgument on the Fragment. Both ViewModels have their custom MvRxState subclass, but in the fragment only common properties (which are defined in let's say AddEditRecipeState) of the state would be used.

Unforunately I can't figure out how to have AddRecipeViewModel and EditRecipeViewModel with a State which subclasses AddEditRecipeState.

I can't figure out how to have two ViewModels implement an Interface and have a state which inherits from. 

In the end I am just trying to re-use my UI within different usecases/viewmodels/business-logic. 

I'm super happy about any thoughts on this, thanks!

**Comment by gpeal** [comment]
@zirkler You can create two fragments that both use the same layout. Would that work?

**Comment by zirkler** [comment]
Unfortunately, that won't help for now simply because the UI is defined in Code (Epoxy), not in layout XML. 

Imaging a different usecase, a "Search Fragment":
On the top of the screen is a Text Input, a RecyclerView shows the search results.
When user inputs text, the "searchTerm: String" property of the state is set, the search is performed by the ViewModel and then the "searchResults: List<String>" property in the state is filled with search results. The fragment then renders all the searchResults in the RecyclerView. 

So the Fragment and ViewModel will look something like this:
```
class SearchFragment {
    private val viewModel: SearchViewModel by activityViewModel()
    override fun epoxyController() = simpleController {
        withState(viewModel) { state ->
            state.searchResults.foreach {
                searchResultCell(
                    id(it)
                    text(it)
                )
            }
        }
    }
}

data class SearchState(
    val searchTerm: String = "",
    val searchResults: List<String> = emptyList()
): MvRxState

class SearchViewModel(
    fun setSearchTerm(searchTerm: String) {
        val results = // search logic ...
        setState { copy(searchResults = results)}
    }
)
```

So now I want e.g. a PeopleSearchViewModel<PeopleSearchState> where the search logic may be different and the state may have additional properties, but the UI/presentation is exactly the same.

I tried something like making the SearchFragment and the SearchState abstract, having a abstract method `getViewModel()` which allows me to aquire whatever kind of ViewModel, but I can't figure out how to make e.g. the PeopleSearchState subclass the SearchState. In general it feels like I'm not using MvRx correctly here.

How would you approach this? I guess in the Airbnb you have quite plenty of usecases where a fragment gets reused. 

Thanks for your time.

**Comment by gpeal** [comment]
@zirkler If it isn't too much code, we have duplicated it in the past. Often, implementations diverge over time (intentionally) and trying to keep the right abstractions often leads to changes for one of the cases accidentally breaking another.

**Comment by zirkler** [comment]
Thanks, that's some really valuable advice. What did you usually do when it was a lot of code to duplicate?

**Comment by gpeal** [comment]
@zirkler Thee is no right answer here. Other things you could consider are moving business logic into other classes that can be injected into your ViewModel, using interface delegation with default implementations, or Fragment subclasses where the shared logic is in the parent and the view model delegate is in the child.
