### ISSUE TITLE
How do I avoid flickering during loading?

### ISSUE THREAD

**Issue by tomtaila** [airbnb/MvRx#369]
My use case is loading data from a Cache and it is causing a flicker in my UI because it loads very quickly.
I would like to essentially say "If loading is quicker than X milliseconds, do not emit Loading" when using `execute`. 

For a typical `Observable` I have the following:

```
fun <T> Observable<T>.debounceIf(predicate: (T) -> Boolean, delay: Long, unit: TimeUnit): Observable<T> {
    return this.debounce {
        when {
            predicate(it) -> Observable.timer(delay, unit)
            else -> Observable.empty()
        }
    }
}
```

**Comment by gpeal** [comment]
@tomtaila What do you display during Uninitialized?

**Comment by tomtaila** [comment]
> @tomtaila What do you display during Uninitialized?

In my use case there is no Uninitialized state. Here's an extremely simplified version of what I'm doing. Imagine the following app, it's a screen 2 UI elements. 
One of the UI elements is a TextView which displays a numerical value. 
The other UI element is a Button.

The state is essentially an `Async<String>` which drives what the TextView displays. It is initialized originally to Success("default str")

Whenever the Button is tapped it generates a random String. For simplicity, let's say I impose a random delay on this between 1ms and 500ms long every time. 

State
```
data class ExampleState(val str: Async<String> = Success("Default Str")): MvRxState
```

ViewModel
```
class ExampleViewModel(
    initialState: ExampleState = ExampleState()
) : BaseMvRxViewModel<UsageScreenState>(initialState) {

    // Called whenever button is tapped
    fun updateString() {
        Single.just(generateRandomString())
            .delay(Random.nextLong(1L, 500L), TimeUnit.MILLISECONDS)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .execute { copy(str = it) }
    }

}
```

Fragment
```

    override fun invalidate() = withState(exampleViewModel) { state ->
        when (state.str) {
            is Success -> {
                textView.text = state.str.invoke()
            }
            is Loading -> {
                textView.text = "Loading"
            }
            is Error -> {
                textView.text = "Error"
            }
            else -> {
                // Do Nothing
           }
        }
    }

```

Ok so say I want to only display "Loading" (i.e. only set state as Loading) whenever the delay is > 50ms

How can I do that? In my first comment this is easy to achieve by using the `Observable` extension and is a great way to avoid "UI flickering" but I am unsure how to do this using MvRx

**Comment by gpeal** [comment]
@tomtaila In your simplified example (if it is an accurate representation), you likely want to have your initial value separate like:
```
data class ExampleState(val defaultStr: String = "Default Str", val asyncStr: Async<String> = Uninitialized): MvRxState {
    val str = asyncStr() ?: defaultStr
}
```

**Comment by tomtaila** [comment]
@gpeal Thanks for getting back to me. I have changed my comment with the example to further simplify as I don't think what you said helps solve my issue unfortunately :(

**Comment by gpeal** [comment]
@tomtaila You can manually wire something up like this. Check for `is Loading && showLoading` to show the loading UI else show the default string.
```
data class ExampleState(val defaultStr = "Hello World", val str: Async<String> = Uninitialized, val showLoading: Boolean = false): MvRxState


class ExampleViewModel(
    initialState: ExampleState = ExampleState()
) : BaseMvRxViewModel<UsageScreenState>(initialState) {
   val loadingJob: Job? = null
    // Called whenever button is tapped
    fun updateString() {
        Single.just(generateRandomString()) // generateRandomString() takes between 1-500ms
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .doOnEvent { 
                  loadingJob?.cancel() 
                  setState { copy(showLoading = false) }
              }
            .execute { copy(str = it) }
        loadingJob = viewModelScope.launch {
             delay(500)
             setState { copy(showLoading = true) }
        }
    }

}


```
