### ISSUE TITLE
State Change

### ISSUE THREAD

**Issue by shubhamR1997** [airbnb/MvRx#370]
How can i change the item of state list. I have a state which is a list and i want to update partiucaler item of that list. If I convert to mutablelist then change it and reert it to immutable list and then change state still it's throwing erro state should be immutable. etc.

It's not a bug just a question Only problem is lack of community support for this framework.

**Comment by haroldadmin** [comment]
To pass the immutability check, you need to create a new list when you need to update some items in it. Converting a list to a mutable list, making some updates to it and then changing it back does not actually create a new list.

Unfortunately Kotlin does not provide any copy/deep-copy methods for lists in the standard library to do this easily, but you can use the `map` method to get a new list from an existing one.

```kotlin
val newList = existingList.map { existingElement ->
  if (shouldReplace(element)) {
    newElement
  } else {
    existingElement
  }
}
```

**Comment by elihart** [comment]
As noted, this is more of a question of kotlin patterns for modifying lists. The `toMutableList()` function does create a new list, so I'm not exactly sure what your issue is. If you can share the code you are using to modify the list that might help.

Here is a helper function we use to update a single item in a list. You could also use a similar approach if you have the item index.
```kotlin
/**
 * Returns a new read only list with the provided item updated.
 *
 * The first item in the pair should be an existing item in the list, and the second item will replace the first.
 */
fun <T> List<T>.copy(vararg pairs: Pair<T, T>): List<T> {
    val mutableList = toMutableList()
    pairs.forEach { (old, new) ->
        val index = mutableList.indexOf(old)
        if (index != -1) {
            mutableList[index] = new
        } else {
            throw IllegalStateException("Item does not exist in the list: $old")
        }
    }
    return mutableList
}
```
