### ISSUE TITLE
Why does Async have `val complete` + how is Loading handled?

### ISSUE THREAD

**Issue by shen-david** [airbnb/MvRx#374]
Just curious how/when this is actually used in the wild. Since `Incomplete` interface also exists, doesn't this just muddy usage patterns by providing two ways of doing the same thing? Or is this meant to be there for flexibility? If so, I'm curious if y'all can share any usage patterns re: these 🙏

**Comment by gpeal** [comment]
@shen-david It's for convenience/readability.
```
when (state.someAsync) {
            is Incomplete -> Unit
            else -> Unit
        }
        if (state.someAsync.complete) {
            Unit
        }
```

Admittedly, I hardly see either used very often.

**Comment by shen-david** [comment]
Gotcha, thanks. I'm also curious about this use case:
1) `setState { Success(results)}`, because I have results from network/db.
2) `setState { Loading()}`, from a user-enacted pull to refresh.
3) I'm waiting for network to come back (and showing a loading spinner). However, I'd like to keep my local results there as well to display them! How should this (common?) use-case be handled?

**Comment by gpeal** [comment]
@shen-david A common way we handle this is to copy the value to a second param of type T? then map the async to Async<Unit>. Then use Async to show the Loader and the T? param to show the data.

**Comment by shen-david** [comment]
ah so like:
```
data class DogState(val asyncDogs: Async<List<Dog>> = Uninitialized, val dogs: List<Dog>)
```
cool, appreciate your quick responses!

**Comment by gpeal** [comment]
@shen-david Yes but we made a quick mapper function so that the data doesn't get hashed twice
```
    private fun <T, V> Async<T>.map(mapper: (T) -> V) = when (this) {
        Uninitialized -> Uninitialized
        is Loading -> Loading()
        is Success -> Success(mapper(this()))
        is Fail -> Fail(error)
    }

...
fun doSomething() {
    observable.execute { copy(data = it(), dataAsync = it.map { Unit }) }
}
```
