### ISSUE TITLE
Having context in MvRxState

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#376]
Sometimes, I would like to have `Context` in `MvRxState`. E.g. it would be useful to have derived properties that are using android string resources.

```
data class SampleState(
    val name: String = ""
) : MvRxState {
    val welcomeMessage = "${context.getString(R.string.welcome)} $name"
}
```

Can I somehow achieve it?

**Comment by gpeal** [comment]
@qbait a MvRxViewModel can outlive a context, particularly across rotations, so you cannot have Context in state.

**Comment by gpeal** [comment]
@qbait You can, however, create functions on your state class that take context and return the formatted message!

**Comment by qbait** [comment]
Thanks @gpeal 
Ofc I wanted to inject Application Context, not Activity Context.

**Comment by gpeal** [comment]
@qbait I would still make a function that takes it as a parameter or inject it into your ViewModel. A state class should just encapsulate the raw data required to render your screen.
