### ISSUE TITLE
Android App Widget with MvRx and Epoxy?

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#380]
Hey guys,
officially `RecyclerView` isn't listed as a remote view available to use in App widget
https://developer.android.com/reference/android/widget/RemoteViews

I see, there is a widget in AirBnb app... I'm, curious if it's possible to use somehow MvRx and Epoxy in App Widget?

**Comment by gpeal** [comment]
@qbait Nope, Widgets are very limited due to the nature of RemoteViews. Neither Epoxy nor MvRx are supported, unfortunately.
