### ISSUE TITLE
sharing ViewModel only in single feature

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#397]
I have a single Activity in my app. Currently, when I want to share ViewModel in the certain feature of my app, I'm using:

`val viewModel: SharedViewModel by activityViewModel()`

When I leave this feature I'm having a function in my `SharedViewModel` that clears state, because, in another way when I come back, everything will be remembered.

Do you recommend anything else that will easily scope my `SharedViewModel` to only one feature (several fragments) so I don't need to clear my state manually?

**Comment by gpeal** [comment]
@qbait You can use a shared parent fragment and `by parentFragmentViewModel()`

**Comment by qbait** [comment]
ok, currently I use Jetpack Navigation with nested navigations, but not nested fragments. In that case, I will refactor my navigations in the future to be able to use  `parentFragmentViewModel()`.
However, is there a way to dispose `activityViewModel()` when I  leave my feature to not keep viewModel in memory by now?

**Comment by qbait** [comment]
Actually, I see that Google introduced this kind of scoping https://stackoverflow.com/questions/56505455/scoping-a-viewmodel-to-multiple-fragments-not-activity-using-the-navigation-co

Would you be interested in implementing it in `MvRxExtensions` (I could create PR) or it's against `MvRx` philosophy to be flexible?

**Comment by gpeal** [comment]
@qbait You can make your own clean up function that calls `setState { YourState() }` and disposes of anything ongoing in it.

https://github.com/airbnb/MvRx/pull/387 may help you there. We may also provide a navigation artifact soon-ish.
