### ISSUE TITLE
Feature to subscribe state from not main thread

### ISSUE THREAD

**Issue by Dugin123** [airbnb/MvRx#402]
This is necessary when the purpose of detecting the state change is a task that requires high performance, not a general purpose.

  Currently, the task can be executed in another thread after state invalidate, but the addition of this feature also prevents concise code amount and thread context switching.

**Comment by gpeal** [comment]
@Dugin123 MvRx 2.0 exposts `viewModel.stateFlow`. You could use that to collect items in whatever context you'd like :)
