### ISSUE TITLE
The Async Loading not called 

### ISSUE THREAD

**Issue by yrickwong** [airbnb/MvRx#407]
the  sample app demo   in  DadJokeIndexViewModel

```
fun fetchNextPage() = withState { state ->
        if (state.request is Loading) return@withState

        dadJokeService
            .search(page = state.jokes.size / JOKES_PER_PAGE + 1, limit = JOKES_PER_PAGE)
            .subscribeOn(Schedulers.io())  //remove this  Loading never called
            .execute { copy(request = it, jokes = jokes + (it()?.results ?: emptyList())) }
    }
```

if remove subscribeOn(Schedulers.io())     the Loading  is not called ever   

withState since  in the background thread , why the add dadJokeService.search() 
 need  add  "subscribeOn(Schedulers.io())"
I'm  confused

**Comment by gpeal** [comment]
@yrickwong Because the actual observable needs to be run on the io thread pool. subscribeOn goes upstream, observeOn goes downstream.

The fact that withState gets queued on a background thread has no effect on the actual API call.

**Comment by yrickwong** [comment]
Thank you, I look at the source code and understand deeply
