### ISSUE TITLE
Wrong kdoc

### ISSUE THREAD

**Issue by digitalbuddha** [airbnb/MvRx#410]
https://github.com/airbnb/MvRx/blob/223bcf5b3a9eb5729f41fbdb672335f845ce8bcb/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMavericksViewModel.kt#L256

Little copy pasta, the comment should read that all properties are subscribed to

**Comment by gpeal** [comment]
It's fixed on the latest. Good catch.
