### ISSUE TITLE
setState "List item changed"  but the view not invalidate

### ISSUE THREAD

**Issue by yrickwong** [airbnb/MvRx#413]
```
data class CheckedData(
    val id: Int,
    val name: String,
    var checked: Boolean = false
)

data class SomeState(val data: List<CheckedData> = emptyList()) : MvRxState

class SomeViewModel(initialState: SomeState) : MvRxViewModel<SomeState>(initialState) {
    fun setChecked(id: Int) {
        setState {
            copy(data = data.find { it.id == id }?.checked = true)
        }
    }
}
```

here is my code ,  
I know the reason because the data of the two SomeState points to the same memory
but how can I elegantly solve the problem of  list item changed  ?

**Comment by gpeal** [comment]
Make checked a val and change the item with `copy(checked = true)`

**Comment by gpeal** [comment]
You can double check that this works by calling `hashCode()` on your data property before and after your call to show that it actually changed and that `hashCode()` works properly on your class
