### ISSUE TITLE
Use state from inside coroutine

### ISSUE THREAD

**Issue by Minirogue** [airbnb/MvRx#417]
I have a feeling this will work in 2.0, but I'm wondering if there is a current workaround or something I'm missing.

I have a call that looks like this
```kotlin
fun refresh() = viewModelScope.launch {
    newSomeStateValue = suspendingFunction(anotherStateValue)
    setState{ copy(someStateValue = newSomeStateValue) }
```
The problem is accessing `anotherStateValue`. If I wrap the inside of the `launch` block with `withState` and use `it.anotherStateValue`, then I can no longer call `suspendingFunction`. I'd like to say `anotherStateValue = withState { it.anotherStateValue }`, but that returns a `Unit`. Is there any way to get the values out of a state outside of the `withState` block?

**Comment by Minirogue** [comment]
Am I correct in that 
```kotlin
var anotherStateValue = 0
withState { anotherStateValue = it.anotherStateValue}
suspendingFunction(anotherStateValue)
```
will result in a race condition?

**Comment by gpeal** [comment]
@Minirogue `anotherStateValue` will be 0 in nearly every case.
https://github.com/airbnb/MvRx/wiki#threading-in-mvrx explains it more

I would do something like:
```
fun refresh() = withState { state ->
   viewModelScope.launch {
      val newSomeStateValue = suspendingFunction(anotherStateValue)
      setState{ copy(someStateValue = newSomeStateValue) }
  }
}

```

**Comment by gpeal** [comment]
If you want to ensure that you have the latest value of `anotherState`, save the Job returned from launch and cancel it before calling launch again

**Comment by Minirogue** [comment]
> ```
> fun refresh() = withState { state ->
>    viewModelScope.launch {
>       val newSomeStateValue = suspendingFunction(state.anotherStateValue)
>       setState{ copy(someStateValue = newSomeStateValue) }
>   }
> }
> ```

I really could have sworn I tried this variation, but it works so I guess not. Thanks @gpeal.

**Comment by Minirogue** [comment]
For the record, this made it untestable because I couldn't call `.join()` on the inner coroutine. I ended up refactoring to `refresh(anotherStateValue)` and changed my calls within the fragment to be inside `withState` calls. 

Hopefully 2.0 will be a little more compatible with wrapping these calls in coroutines.
