### ISSUE TITLE
Getting Fragment arguments when using activityViewModel

### ISSUE THREAD

**Issue by deRonbrown** [airbnb/MvRx#423]
I'm currently using `androidx.navigation` and having some trouble getting access to the `Fragment` arguments in the `MvRxViewModelFactory` when I convert the `Fragment` from using `by fragmentViewModel` to `by activityViewModel`.

Current setup:
```
data class ExampleState(val title: String = "") : MvRxState

class ExampleViewModel(
    initialState: ExampleState,
    argsLazy: NavArgsLazy<ExampleFragmentArgs>
) : BaseMvRxViewModel<ExampleState>(initialState {
    init {
        val modelId = argsLazy.value.modelId
        // Do something with modelId
    }

    companion object : MvRxViewModelFactory<ExampleViewModel, ExampleState> {
        @JvmStatic
        override fun create(viewModelContext: ViewModelContext, state: ExampleState): ExampleViewModel {
            val fragment = (viewModelContext as FragmentViewModelContext).fragment<ExampleFragment>()
            return ExampleViewModel(state, fragment.navArgs())
        }
    }
}

class ExampleFragment : BaseMvRxFragment() {
    private val viewModel: ExampleViewModel by fragmentViewModel()

    override fun invalidate() {
    }
```

My plan is for `ExampleFragment` to show a `BottomSheetDialogFragment`. This `DialogFragment` should share the `ExampleFragment` view model instead of creating its own. Therefore, I want to scope the `ExampleFragment` view model to the `Activity` and then use `by existingViewModel` in the `DialogFragment`.

However, when I change to the following:
```
private val viewModel: ExampleViewModel by activityViewModel()
```
the `MvRxViewModelFactory` gets an `ActivityViewModelContext`.

How can I get access to the `Fragment` arguments from `ActivityViewModelContext`?

**Comment by gpeal** [comment]
@deRonbrown There's a bit of a catch 22 there. Activity is a larger scope than Fragment so we can't provide anything Fragment specific to something with the Activity lifecycle. Can your bottom sheet be a child fragment instead? Then you can use `by parentFragmentViewModel()` in the bottom sheet and keep the main fragment as a fragment view model.

**Comment by deRonbrown** [comment]
Thanks for the reply. And yeah, I originally went down the route of using a child Fragment, but DialogFragments aren't nested. I settled on setting the presenting fragment as the target of the DialogFragment and then using `by targetFragmentViewModel()`.
