### ISSUE TITLE
by fragmentViewModel() error -> "Not enough information to infer type variable VM"

### ISSUE THREAD

**Issue by Harsh-Jagad** [airbnb/MvRx#424]
Hello,

I encountered an error with the delegate provider `by fragmentViewModel()` after switching to 2.0.0-alpha2  👇🏻.

<img width="716" alt="Screenshot 2020-07-03 at 17 13 14" src="https://user-images.githubusercontent.com/32385784/86485955-fba33800-bd51-11ea-824d-2207f330c216.png">

Everything appears to work as expected when running the app however I would like to resolve this error if possible.

Is there a way to do this?

Thank you (for your time and effort in creating this fantastic framework and for sharing it with us).

**Comment by gpeal** [comment]
@Harsh-Jagad Might be a local IDE issue? Alpha 4 is working without issues for us.

**Comment by gpeal** [comment]
Can you reopen if that is not the case?

**Comment by elihart** [comment]
I have also seen this, as have coworkers. It may be due to something like disabling new type inference in the IDE, or may simply be a kotlin/Studio bug. I don't think there is anything we can do and it should be solved with kotlin 1.4.0
