### ISSUE TITLE
MvRxFragment undefined

### ISSUE THREAD

**Issue by martymiller** [airbnb/MvRx#425]
Hi, I'm new to this library and am going through the tutorial.  

The sample code mentions MvRxFragment here:

```
class MyFragment : MvRxFragment() {
    private val viewModel: MyViewModel by fragmentViewModel()

    override fun invalidate() = withState(viewModel) { state ->
        loadingView.isVisible = state.listing is Loading
        titleView.text = listing()?.title
    }
}
```
Yet, my compiler doesn't recognize it as a class.  I see a BaseMvRxFragment class, but the sample code doesn't mention this.  Is the documentation wrong, or am I missing something?

There's even a link to it
https://github.com/airbnb/MvRx/wiki/MvRx-at-Airbnb#mvrxfragment

**Comment by gpeal** [comment]
@martymiller The documentation could be more clear. `MvRxFragment` there is supposed to represent whatever the base fragment is for your app. If there isn't one, it's just `BaseMvRxFragment`

In MvRx 2, it'll just be an interface `MvRxView` which means you just add instead of using a base class.
