### ISSUE TITLE
Kotlin 1.4 not support

### ISSUE THREAD

**Issue by Dugin123** [airbnb/MvRx#433]
Kotlin 1.4 not support

```
private val mediaLoadVM  by fragmentViewModel(MediaLoadViewModel::class)

Type 'MvRxDelegateProvider<TypeVariable(T), TypeVariable(VM)>' has no method 'getValue(MediaLoadFragment, KProperty<*>)' and thus it cannot serve as a delegate
```

**Comment by gpeal** [comment]
I encountered this as well. We'll take a look.

**Comment by gpeal** [comment]
@Dugin123 Are you using 2.0?

**Comment by gpeal** [comment]
I've filed an issue with Jetbrains
https://youtrack.jetbrains.com/issue/KT-41135

**Comment by gpeal** [comment]
The issue has been fixed and is slated for 1.4.10

**Comment by kaushalyap** [comment]
[Kotlin 1.4.10](https://github.com/JetBrains/kotlin/releases/tag/v1.4.10) was released!

**Comment by gpeal** [comment]
Yup! We did the upgrade at Tonal and it seems to be working great now! I'm going to close this one out.
