### ISSUE TITLE
Chmod mockPrinter 

### ISSUE THREAD

**Issue by digitalbuddha** [airbnb/MvRx#434]
I was going through the wiki and clicked in the link to download the executable for the mock printer, I then ran into a missing permission: 
```
 ./MvRxMockPrinter
 zsh: permission denied: ./MvRxMockPrinter
 miken@Mikes-Mac Downloads % sudo ./MvRxMockPrinter
 sudo: ./MvRxMockPrinter: command not found
```

Chmod did the trick

**Comment by elihart** [comment]
Fixed in beta1
