### ISSUE TITLE
How about `setState` but not call invalidate in MvRxView?

### ISSUE THREAD

**Issue by dinhlamvn** [airbnb/MvRx#441]
Now, follow the MvRx, we will call `invalidate` in MvRxView when the `state` has changed. But sometime, we don't need to invalidate `view`, such as `Input text to the EditText`, I want to set `inputStr` into `state`, but I don't want invalidate the view, that make bad UX for user?

How about a function such as: `setStateIgnoreInvalidate..`. I think it is helpful in some case. 👍

**Comment by gpeal** [comment]
@dinhlamvn This violates the notion that you screen is a function of your ViewModel state. Ideally, your views are idempotent, meaning you can set the same state on them multiple times in a row with very little overhead. In your case, you may want to do something like:
```
override fun onCreate(savedInstanceState: Bundle?) {
    viewModel.selectSubscribe(YourState::inputStr) { inputStr ->
        editText.text = inputStr
    }
}
```

So here, for a specific view, you can only update it when a specific state property changes.

**Comment by jinqisong** [comment]
How to use it in 2.0?

**Comment by gpeal** [comment]
@jingjingduan `onEach` instead of `selectSubscribe`
