### ISSUE TITLE
MvRx repo or app showcase

### ISSUE THREAD

**Issue by rizmaulana** [airbnb/MvRx#448]
Hi, I've been using MvRx on my latest project, it's such a great framework, but I was wondering what app / company that already implements MvRx on its production.

I've been going through out all the sample app but still cannot find how to implement MvRx properly on production / real world application, I believe that MvRx has more advantages than how I implement it now on my latest project. 

It will be great if you can add app or repo showcase on readme (or somewhere else) then another developers can unlock more advantages when they adopt MvRx to their project.

Thank you,

**Comment by gpeal** [comment]
@rizmaulana Airbnb, Tonal, Dropbox, Turo, (maybe) Netflix, and many other companies are using it successfully in production. What specific kind of information would be useful?
