### ISSUE TITLE
MvRx 2.0.0-beta01 Getting viewModel from Fragment throw a exception

### ISSUE THREAD

**Issue by eric-ampire** [airbnb/MvRx#457]
In MvRx 2.0.0-beta01 Getting viewModel from Fragment throw an exception

`private val viewModel: LoginViewModel by fragmentViewModel()`

Type 'MavericksDelegateProvider<TypeVariable(T), TypeVariable(VM)>' has no method 'getValue(LoginFragment, KProperty<*>)' and thus it cannot serve as a delegate

**Comment by gpeal** [comment]
@eric-ampire Can you include a sample? You must use Kotlin 1.3.72 or 1.4.10, not 1.4.0.

**Comment by elihart** [comment]
I think this can happen if the delegate is used as a local property inside a function, which does not currently work because of a kotlin 1.4 bug

**Comment by GolnazTorabi** [comment]
I Have the same problem as eric

**Comment by gpeal** [comment]
@GolnazTorabi Are you using Kotlin 1.4.0? If so, try upgrading and it should go away.

**Comment by GolnazTorabi** [comment]
I change it to 1.3.72 and 1.4.10 and  I still have the problem.
This is my ViewModel:
MyViewModel (initialState: State, private val repository: Repository) :
    MvRxViewModel<\State>(initialState)
And I initialize it like below
 private val viewModel: MyViewModel by fragmentViewModel()
but it still don't know fragmentViewModel()

**Comment by gpeal** [comment]
@GolnazTorabi can you attach a project that repros that?

**Comment by GolnazTorabi** [comment]
https://github.com/GolnazTorabi/FoodDelivery 
This is the project I used in menuFragment, PizzaFragment, SushiFragment, DrinkFragment

**Comment by gpeal** [comment]
@GolnazTorabi Your Fragment has to implement `MavericksView`.

@eric-ampire did you forget to implement `MavericksView` too?

**Comment by GolnazTorabi** [comment]
Thank you in samples it does not implement MavericksView, because of that I made a mistake.

**Comment by gpeal** [comment]
@GolnazTorabi glad we were able to get it resolved!
