### ISSUE TITLE
[2.0.0-beta1] setState{} is invoked multiple times in unit tests executed with MvRxTestRule

### ISSUE THREAD

**Issue by pwillmann** [airbnb/MvRx#466]
MvRx: `2.0.0-beta1`
Kotlin: `1.4.10`

When running unit tests for a MavericksViewModel I noticed that `setState{}` is called multiple times due to `MvRxTestRule` initializing `MockableMavericks` which in turn means the `MockableMavericksStateStore` is used, which in turn invokes the `stateReducer()` immediately and then passes it to two other StateStores that then also invoke the reducer. 

Given a method like the following in the ViewModel: 
```
   fun login() = withState {state ->
        if (state.loginAsync is Loading) {
            return@withState
        }

        suspend { authRepository.loginUser(email = state.email!!, password = state.password!!) }
            .execute(ioDispatcher) { loginAsync ->
                if (loginAsync is Success) {
                    viewModelScope.launch {
                        sideEffect.onLogin(loginAsync())
                    }
                }

                copy(loginAsync = loginAsync)
            }
    }
``` 

it is impossible to verify the sideEffect function was called one time, because it will be called three times due to the reducer being invoked three times.

**Comment by elihart** [comment]
yes, this is an undocumented change in how reducers work in tests. However, there is a core mvrx principle that reducer functions should _not_ have any side effects. While we could maybe redesign the testing/mocking infra to avoid invoking the reducer multiple times I don't think it is good to encourage reducers with side effects.

Instead the general recommendation would be to subscribe to the `loginAsync` property, or you could have your test verify at least one or more interactions instead of just one

**Comment by pwillmann** [comment]
I agree, for some reason it never occured to me, that you can also subscribe to properties within the ViewModel itself and not just from fragments 🤦 . Thanks for your help!

**Comment by digitalbuddha** [comment]
if someone needs to have code that only is called once...for example we had analytics that got called too many times in tests run this after your test rule init

```
Mavericks.initialize(
                false,
                MyMavericksViewModelConfigFactory())


class MyMavericksViewModelConfigFactory: MavericksViewModelConfigFactory(debugMode = false){

    override fun <S : MavericksState> buildConfig(
            viewModel: MavericksViewModel<S>,
            initialState: S
    ): MavericksViewModelConfig<S> {
        val scope = coroutineScope()
        return object: MavericksViewModelConfig<S>(debugMode, SynchronousMavericksStateStore(initialState, scope), scope) {
            override fun <S : MavericksState> onExecute(viewModel: MavericksViewModel<S>): BlockExecutions {
                return BlockExecutions.Completely
            }
        }
    }
}```
