### ISSUE TITLE
How to extend DialogFragments?

### ISSUE THREAD

**Issue by DRC9702** [airbnb/MvRx#467]
How do DialogFragments fit into this framework?

In order to properly build Dialogs, common android practice is to build `AlertDialog`s from `DialogFragment`s (instead of directly manipulating the dialog itself). 

In order to utilize MVVM properly with MvRx, every fragment must extend `BaseMvRxFragment`. In these child classes, you can then access ViewModels to do any necessary logic. 

However, this presents an issue as you can't have double inheritance (`BaseMvRxFragment` only extends the `Fragment` class). What's the proper way to build re-usable Dialogs (I want to use them across multiple screens because of the repeated functionality) with MvRx?

One thing I can do is just build my own `BaseMvRxDialogFragment` class by extending `DialogFragment` and copying the <30 lines of methods from `BaseMvRxFragment` in order to create my own implementation, but I"m not sure if this will break some underlying databinding/injection/etc.

Currently, it seems the approach is to just build android views and treat them as part of each fragment (part of the View in M-View-VM) while directly manipulating Dialogs. But this requires duplicated code across multiple screens on my app, whereas I would like to treat each Dialog as its own separate encapsulated flow that you can enter from different entry points/fragments.

To compensate (but not actually fix), my strategy right now is just to treat my dialogs as Views with their own ViewModel and then have every Fragment extend a BaseFragment class that has each of these dialogViewModels as a property. This works, but is not ideal since it adds a large amount of unnecessary logic to unrelated screens (albeit, through a superclass).

What's the correct way to do this? Thank you.

**Comment by pwillmann** [comment]
I think using  a`BaseMvRxDialogFragment` and copying over the few lines from the `BaseMvRxFragment` is a valid approach here. Databinding and Injection should not be an issue since the `BaseMvRxFragment` is not really doing anything related to that.

**Comment by gpeal** [comment]
@DRC9702 You can use 2.0.0-beta1. It replaced MvRxFragment with an interface, `MavericksView`.
If you use `mvrx-rxjava2-2.0.0-beta1`, it should be a drop in replacement. If you only use coroutines, you can just use `mvrx:2.0.0-beta1` but note that the library is getting renamed Mavericks so the class names have changed,

https://github.com/airbnb/MvRx/blob/release/2.0.0/docs/new-2x.md
