### ISSUE TITLE
ViewModels subscribing to other ViewModels

### ISSUE THREAD

**Issue by nullptr2this** [airbnb/MvRx#471]
Firstly, great library and thanks for sharing it.  A question about intended use of a particular view model method.

BaseMvRxViewModel defines the following method:

```
    /**
     * For ViewModels that want to subscribe to another ViewModel.
     */
    protected fun <S : MvRxState> subscribe(
        viewModel: BaseMvRxViewModel<S>,
        subscriber: (S) -> Unit
    ) {
        assertSubscribeToDifferentViewModel(viewModel)
        viewModel.subscribe(lifecycleOwner, RedeliverOnStart, subscriber)
    }
```

Is the intention that view models be composed?  Like ViewModelA is injected with ViewModelB and then observes ViewModelB (and if so are there recommendations for accessing ViewModelB during ViewModelA's instantiation via it's factory)?  Or is the intent more to wire up view models from their clients?  Like in a fragment, have the fragment pass ViewModelB to ViewModelA like

```
viewModelA.observe(viewModelB)
```

where the `ViewModelA::observe` method is implemented using the `subscribe` method shown above?

```
fun observe(viewModelB: ViewModelB) {
    subscribe(viewModelB) { stateB ->
         //REACT!!!
    }
}
```

Any thoughts on usage of this method from a best practices for MvRx standpoint?

**Comment by gpeal** [comment]
@nullptr2this Yes, that's correct. We don't do it very often but it's there because from time to time, it can be useful.

In MvRx 2.0 (currently beta2 but production ready), the base view model exposes `val stateFlow: Flow<S>` which you can use to compose the state with anything you want.

**Comment by nullptr2this** [comment]
Thanks!
