### ISSUE TITLE
Fail<T> equals method doesn't compare exceptions properly

### ISSUE THREAD

**Issue by Lamorak** [airbnb/MvRx#481]
This assertion should succeed:

    @Test
    fun test() {
        val fail = Fail<String>(TestException())
        val fail2 = Fail<String>(TestException())

        assertEquals(fail, fail2) // fails
    }

    class TestException : Exception("Testing error")

**Comment by gpeal** [comment]
@Lamorak Why? The stack traces are different.

**Comment by Lamorak** [comment]
Well first it's very contra intuitive because if the exceptions are equal, you'd expect the `Fail` wrappers to also be equal. Second, this essentially prohibits any testing with failed state because no two `Fail`s will ever be equal (unless they somehow hold the same instance of exception).
I suggest to just use the exception's `equals` method bucause it should know best which two exceptions are equal after all.

**Comment by gpeal** [comment]
@Lamorak The exceptions are not equal though. They were thrown on different lines therefore they have different stack traces and represent different exceptions.
For testing, the recommended approach is to create your exception once and check for it both times.

**Comment by Lamorak** [comment]
@gpeal Why doesn't the provided sample work? The exceptions weren;t even thrown yet and should have no stack traces.
I do create one exception and check for it in the test, but as you know exceptions are not immutable therefore the check fails.

**Comment by gpeal** [comment]
@Lamorak Your test fails because the two exceptions have different stack traces because they were created on different lines of code.

**Comment by gpeal** [comment]
I'm going to close this because I don't think it is an issue for the reasons above. Feel free to reopen it if you feel otherwise.
