### ISSUE TITLE
Invalidate execution for rapidly changing actions

### ISSUE THREAD

**Issue by xMickeymikex** [airbnb/MvRx#482]
Hello,

I have a question about storing rapidly changing data in state. Is it a good approach to store this kind of data in state as it is required for screen rendering? Is there a way of ignoring some variables in state so that invalidate does not get called?

For example i have a progress value (0...100) which changes every second and i want to update my progress bar value to specified value, which i am doing with individual subscription. However i don't want invalidate to be called each time progress value changes, because it forces many other views to redraw itself.

**Comment by elihart** [comment]
This is generally fine to do. There is no way to have some pieces of state be ignored.

If the update is every second that really isn't that often. The crucial part is that your UI should be smart about only redraws the relevant views affected by the change. This can be done via subscribing to the specific property and updating the view in the callback, using Jetpack Compose and having a Composable that just depend on the changing state, or using a Recyclerview and relying on intelligent diffing (Epoxy helps a lot with this, and does its work async)

If you had data changes that were happening many times per second that might start to be too much, and mvrx may not be designed for that use case.

**Comment by gpeal** [comment]
Agreed, this shouldn't be a problem. Changes made in invalidate should also be [idempotent](https://en.wikipedia.org/wiki/Idempotence) so if they are called multiple times, it should result in minimal or zero overhead.

You are, of course, free to have your own `StateFlow` property in your ViewModel if you want to keep high frequency data out of your main state class.
