### ISSUE TITLE
copy in withState sometimes not triggering EpoxyController 

### ISSUE THREAD

**Issue by oldsport76** [airbnb/MvRx#485]
I'm using MvRx with Epoxy. I have a list of items in my state that I update with `copy()` in the `withState` closure. Sometimes when I update the state, the `EpoxyController` in my `Fragment` is not prompted to update the UI. Is there any reason for which the `Epoxy Controller` might not be prompted to update the UI on a state change?

**Comment by elihart** [comment]
this completely depends on your specific code and how you have everything configured. When done correctly this should not happen, so you likely have a bug in your code.

**Comment by gpeal** [comment]
@oldsport76 Do you mean `setState` closure? withState will never update your staet.

**Comment by elihart** [comment]
Also, you said you are doing a copy update in `withState` which would be wrong. I am assuming you mean `setState`

**Comment by oldsport76** [comment]
No, I do indeed update my states with a `copy()` call at the end of a `withState` closure. For example, I do it as follows:

```
fun loadEvents() = withState { state ->
        if (state.loadEventsRequest is Loading) return@withState

       eventsRepo.getEvents()
        .execute {
            copy(loadEventsRequest = it, events = it().orEmpty())
        }
}

I write the logic in the rest of my app analogously and have never had any problems.

**Comment by elihart** [comment]
In your example `withState` is irrelevant - the `execute` block is what matters and is what the `copy` function applies to.

your code looks fine, I would guess either your UI is not properly setup to rerender on state changes, or your state doens't properly implement equals/hashcode, or your epoxy model's don't properly implement equals/hashcode

**Comment by oldsport76** [comment]
I've noticed that this behavior occurs when only certain fields in my `Event` model change in the `events` list. I believe the problem lies in the `equals/hashcode` aspect. I'll investigate. Thanks.

**Comment by gpeal** [comment]
@oldsport76 I'm going to close this for now. If you are able to repro an issue with mavericks 2.0 in a sample project, feel free to reopen this.
