### ISSUE TITLE
AsyncSubscribe vs Invalidate order question

### ISSUE THREAD

**Issue by sanogueralorenzo** [airbnb/MvRx#486]
Hello 👋 I wanted to check if `invalidate` being called before `asyncSubscribe` is an expected behaviour, and if it is, is there any alternative to fixing the issue below?

Given a ViewModel with something like:
```kotlin
class ExampleViewModel @AssistedInject constructor(
    @Assisted state: ExampleState,
    private val repository: ExampleRepository
) : MavericksViewModel<ExampleState>(state) {

    // saveInfo is an Rx2 Completable and submitResult is Async<Unit>
    fun onSubmitClick() = repository.saveInfo().execute { result -> copy(submitResult = result) }
}
```

& given a Fragment with something like:
```kotlin
class ExampleFragment : ContainerFragment() {

    private val viewModel: ExampleViewModel by fragmentViewModel()

    private val button: ButtonOptions =
        ButtonOptions.SingleButton(StringResource.Id(R.string.save), { viewModel.onSubmitClick() })

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel.asyncSubscribe(
            asyncProp = ExampleState::submitResult,
            deliveryMode = uniqueOnly(),
            onSuccess = { requireActivity().finish() },
            onFail = { showError(it) }
        )
    }

    // some epoxy controller code

    override fun invalidate() = withState(viewModel) { state ->
        super.invalidate()
        showLoading(state.isLoading)
    }
}
```

When you press the submit button and call `.execute` the following happens:
- loading is shown on the screen (I've tried having loading as part of the controller but the issue is still the same)
- api call happens
- when api call finishes, you can see how the loading disappears for a small fraction of time and then the screen closes

This can be easily fixed by updating the `state.isLoading` from
```kotlin
val isLoading: Boolean
    get() = loadReportResult is Loading || submitResult is Loading
```

to 

```kotlin
val isLoading: Boolean
    get() = loadInitialInformation is Loading || submitResult is Loading || submitResult is Success
```

While this fixes the issue and makes sense from a state perspective, I think it can be easy to miss when doing the day to day screens. Is there another alternative in which we can avoid the loading hiding & screen finishing straight away?

Thank you 🙏

**Comment by gpeal** [comment]
invalidate will almost certainly happen after all subscribers. Subscribers are called synchronously but invalidate is actually posted until the next frame so it never gets called more than once per frame (that happens [here](https://github.com/airbnb/MvRx/blob/689c2e791d4a91ee2b446835b7fed72211602c56/mvrx/src/main/kotlin/com/airbnb/mvrx/ViewModelDelegateProvider.kt#L94)).

I think the issue might be that finish isn't immediate right?

**Comment by sanogueralorenzo** [comment]
🤦 yeah makes sense, simple logging also show the order is the opposite of what I assumed

how would you handle this situation though? is the best approach keeping the state solid with a `submitResult is Success` on submission & close scenarios to avoid the flashing?

**Comment by gpeal** [comment]
@sanogueralorenzo if you know that the screen will always exit on completion, you could add `is Success` to the loading state with a comment or something even though it seems counter intuitive at first.

**Comment by sanogueralorenzo** [comment]
Thanks! Closing this, thanks for the clarification.
