### ISSUE TITLE
Couldn't find the class BaseMvRxViewModel<S>

### ISSUE THREAD

**Issue by JagadeeshDamarasingu** [airbnb/MvRx#497]
I am following along the documentation, 

when I am trying to create a generic class for my ViewModels like:

```
abstract class MvRxViewModel<S : MavericksState>(initialState: S) : BaseMvRxViewModel<S>(
  initialState = initialState,
  debugMode = BuildConfig.DEBUG
) 
```

I am unable to find the BaseMvRxViewModel class. Is it removed/renamed from new releases ?

**Comment by gpeal** [comment]
@JagadeeshDamarasingu Are you using 2.0? If so, it's `MavericksViewModel`. We're working on getting the new docs hosted but for now, they are [here](https://github.com/airbnb/MvRx/tree/master/docs)

**Comment by JagadeeshDamarasingu** [comment]
@gpeal I'm using `2.0.0-beta3`, But I see that `MavericksViewModel` isn't extending Jetpack's ViewModel. I'll check the documentation.

**Comment by JagadeeshDamarasingu** [comment]
I see that above point is mentioned in new docs, thanks for quick reply
