### ISSUE TITLE
Where do dialogs/snackbars/etc fit into MvRx?

### ISSUE THREAD

**Issue by SamThompson** [airbnb/MvRx#60]
I'd be curious to know how transient ui elements like dialogs/snackbars/etc fit into the overall MvRx pattern (if at all). Is it something like a flag on the state? Or is that outside of the scope of what MvRx is managing?

**Comment by gpeal** [comment]
Subscribe to state changes. We use `asyncSubscribe` like:
```
fun onViewCreated(...) {
    viewModes.asyncSubscribe(YourState::asyncProp, onFail = {
        Snackbar.make(...).show
    {
}
```

**Comment by SamThompson** [comment]
Thanks for the info!
