### ISSUE TITLE
Avoid rebind views without Epoxy.

### ISSUE THREAD

**Issue by wbinarytree** [airbnb/MvRx#63]
In the wiki, it said 

>Views should be considered ephemeral. invalidate() will be called every time state changes. As a result, you should use something like epoxy or optimize your view's setters to no-op if the same data is set again.

I can understand that in Android there are no mechanism for avoid rebind the same date to a view and prevent re-draw UI. 
But except epoxy ,is there any recommended way for doing that? I don't really want to re-layout my  screens in an RecyclerView.

Another problem is that, as I can imagine. When the business logic /screen become more complex. The MvRxState can have tons of parameters. Won't it be a problem to manage?

**Comment by creati8e** [comment]
@wbinarytree just use DiffUtils

**Comment by gpeal** [comment]
@creati8e answer is correct. You can even use [AsyncListDiffer](https://developer.android.com/reference/android/support/v7/recyclerview/extensions/AsyncListDiffer) to have it run on a bg thread (which Epoxy can also do).
