### ISSUE TITLE
Work with Dagger

### ISSUE THREAD

**Issue by chrisbanes** [airbnb/MvRx#69]
At the moment I see no way of integrating with an existing ViewModelProvider.Factory. This is necessary to be able to use Dagger to inject ViewModels.

[Example fragment](https://github.com/chrisbanes/tivi/blob/master/app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt#L63)

Is there a way?

**Comment by chrisbanes** [comment]
I settled on the following for now [commit](https://github.com/chrisbanes/tivi/blob/06727520434034e6c54b4a8b112d050872c96a31/app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt#L58)

I inject the ViewModel.Factory into the Activity, then that to create the VM. Works nicely but we do lose the initial state nice-ness.

**Comment by gpeal** [comment]
@chrisbanes The reason we moved away from that is because initialState is pretty critical to MvRx. This would prevent a ViewModel from being able to use Fragment args or for MvRx to do proper ViewModel restoration in a new process.

Thoughts?

**Comment by chrisbanes** [comment]
Yeah, we don't have assisted DI with Dagger so it's hard to get the initialState + fragment args working nicely.

I managed to get it sort of working, but I can't rely on `init {}` and have to manually poke the VM to use the fragment args: [here](https://github.com/chrisbanes/tivi/blob/cacf79fed811956b121fd17e742aca764e5a136e/app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt#L58).

I might have a play with AutoFactory and see if I can get it to work.

**Comment by chrisbanes** [comment]
Renaming this to be clearer what the goal is (for me anyway).

I got AutoFactory working [here](https://github.com/chrisbanes/tivi/pull/212/commits/aff85d779d26db1ccbbe274ea60b3bd7e8e293ed). The only downside I see is that `MvRxViewModelFactory` only passes along the Activity, whereas I would much rather inject the related fragment instead.

Can we get a version of `MvRxViewModelFactory` which provides the Fragment?

**Comment by mzgreen** [comment]
@chrisbanes have you seen this: https://github.com/square/AssistedInject ? Maybe it'll be helpful in this scenario?

**Comment by chrisbanes** [comment]
@mzgreen Ah yes! I've been wanting a reason to try it but totally forgot about it. I'll try on Monday.

**Comment by chrisbanes** [comment]
Moving over to https://github.com/square/AssistedInject in https://github.com/chrisbanes/tivi/pull/214

**Comment by gpeal** [comment]
@chrisbanes I implemented AssistedInject at Tonal and it's working great! Thank you for putting in that work. I'll try and make a wiki page for it.

**Comment by marukami** [comment]
@chrisbanes I was not able to find a way to create a Dagger `ViewModelProvider.Factory`, But, I did find a nice-ish way to inject a `ViewModelFactory` `Provider` map via the activity. Here is all the boilerplate 
https://gist.github.com/marukami/3024dd7ae399a4a33df3041a9af84401

Here is the ViewModel example; I can't get my head around how I would remove the downcast and keep dagger happy.
```kotlin
class MyViewModel @AssistedInject constructor(
  @Assisted state: MvRxState,
  private val api: Api
) : MvRxViewModel<MyViewModelState>(state as MyViewModelState) {

  @AssistedInject.Factory
  interface Factory : ViewModelFactory {
    override fun create(state: MvRxState): MyViewModel
  }

  companion object : MvRxViewModelFactory<MyViewModelState> {
    @JvmStatic override fun create(
      activity: FragmentActivity,
      state: MyViewModelState
    ): BaseMvRxViewModel<MyViewModelState> =
      activity.daggerCreate(
        factory = MyViewModel.Factory::class.java,
        state = state
      )
  }
}
```

**Comment by chrisbanes** [comment]
@marukami You need to create an `AssistedInject.Factory` for each ViewModel.

Example: https://github.com/chrisbanes/tivi/blob/master/app/src/main/java/app/tivi/showdetails/episodedetails/EpisodeDetailsViewModel.kt#L54

**Comment by TheLester** [comment]
It would be nice to have `MvRxViewModelFactory` with provided fragment, as @chrisbanes mentioned. Otherwise, activity should hold all the viewmodel's factories.

**Comment by marukami** [comment]
I have been using a fork I made that adds a fragment factory #148. 

With the fork, you can use the `AssistedInject` to inject the fragment and then call the factory in the `Fragment` from the factory like how @chrisbanes was doing with an `Activity` `ViewModel`. 

```kotlin
class MyFragment :
  BaseMvRxFragment() {
  @Inject lateinit var viewModelFactory: MyViewModel.Factory
}

class MyViewModel @AssistedInject constructor(
  @Assisted state: MyState,
  private val api: TestApi
) : MvRxViewModel<MyState>(state) {

  @AssistedInject.Factory
  interface Factory : ViewModelFactory<MyState> {
    override fun create(state: MyState): MyViewModel
  }

  companion object : MvRxFragmentViewModelFactory<MyState> {
    @JvmStatic override fun create(
      fragment: Fragment,
      state: MyState
    ): BaseMvRxViewModel<MyState> =
      (fragment as MyFragment).viewModelFactory.create(state)
  }

}
``` 

Any feedback on doing it this way would be awesome.

**Comment by pwillmann** [comment]
Looks good to me, this would really help using MvRx in dagger projects with multiple gradle modules, where not every module has its own activity.  

Can we merge this @gpeal ?

**Comment by gpeal** [comment]
@pwillmann We weren't able to merge that change, unfortunately. You can follow that discussion [here](https://github.com/airbnb/MvRx/pull/197).

**Comment by gpeal** [comment]
However, the [tivi app ](https://github.com/chrisbanes/tivi) from @chrisbanes was able to use AssistedInject and in our app, we use a MvRxViewModelFactory and manually get the dependencies from the component to do constructor injection. I'm going to close this issue for now since I'm not sure if there is anything actionable at this point.
