### ISSUE TITLE
execute() sets subscribeOn() scheduler

### ISSUE THREAD

**Issue by chrisbanes** [airbnb/MvRx#70]
Looking at execute(), it seems to set the subscribeOn() scheduler to be the single threaded background subscriber the VM keeps. While I can see why the observeOn() scheduler is set, I don't see why you force the actual subscription on the same scheduler.

All of my observables are coming from a database, so I want them on the io() scheduler ideally.

**Comment by hellohuanlin** [comment]
@chrisbanes your upstream database call should `subscribeOn(io)`. The downstream `subscribeOn` in VM will be a no-op.

**Comment by chrisbanes** [comment]
The observer should be forced, but the subscribe should not be touching the state at all and I see no reason to restrict.

@hellohuanlin relying on that feels flakey. It only takes a small behaviour change in Rx to break that.

**Comment by hellohuanlin** [comment]
@chrisbanes I agree that it's pretty strange and unexpected to have downstream switching threads for the upstream operation.

**Comment by Oknesif** [comment]
As I can see, PR for this issue is here: https://github.com/airbnb/MvRx/pull/75

**Comment by gpeal** [comment]
Yes, this was fixed in #75
