### ISSUE TITLE
MvRxLifecycleAwareObserver depends on internal RxJava APIs

### ISSUE THREAD

**Issue by ZacSweers** [airbnb/MvRx#74]
FYI. In AutoDispose we copied out things as needed to avoid this

**Comment by jpventura** [comment]
@BenSchwab @elihart @gpeal does #347 (i.e. refactor to Kotlin coroutines) also solves this issue?

**Comment by gpeal** [comment]
Yup!

**Comment by gpeal** [comment]
Fixed as this is now all coroutines under the hood
