### ISSUE TITLE
Wrong emit order (Loading after Success)

### ISSUE THREAD

**Issue by chrisbanes** [airbnb/MvRx#76]
I've noticed a bit of weirdness since moving to MvRx. After debugging it today, it turns out that the emitting order using `execute()` is wrong for Observables which emit immediately:

``` kotlin
D  imageProviderObservable reducer: Success(value=app.tivi.tmdb.TmdbImageUrlProvider@696bcd)
D  imageProviderObservable reducer: com.airbnb.mvrx.Loading@7749791c
```

imageProviderObservable in this instance is a `BehaviorSubject` with a default value, so will always emit immediately on subscribe. If the Observable does not emit again, the final state is `Loading` which is obviously wrong.

**Comment by hellohuanlin** [comment]
@chrisbanes `Loading` should be emitted before subscription to the observable happens. 

https://github.com/airbnb/MvRx/blob/master/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt#L141-L152

Can you try to debug there?

**Comment by chrisbanes** [comment]
Yep I saw the code but haven't had a chance to step back into MvRx yet (I won't be able to until Monday now).

**Comment by gpeal** [comment]
[This test](https://github.com/airbnb/MvRx/blob/master/mvrx/src/test/kotlin/com/airbnb/mvrx/ViewModelSubscriberTest.kt#L102) also passes. If this could be reproduced with a failing test, that would be great.

**Comment by chrisbanes** [comment]
Closing this. I can't recreate in tests, and I think I've worked out a bug in my app which is causing this. Thanks!
