### ISSUE TITLE
One-off events

### ISSUE THREAD

**Issue by ATizik** [airbnb/MvRx#80]
In google samples certain events are propagated through [SingleLiveEvent](https://github.com/googlesamples/android-architecture/blob/dev-todo-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/SingleLiveEvent.java).

While this concept goes against MVI principle, it's needed in certain cases to greatly reduce boilerplate. For example, to show toast in current implementation I have to create a property inside my state, and inside `View` send an event back to `ViewModel` telling it that toast was shown. 

Another [similar solution](https://github.com/fabioCollini/ArchitectureComponentsDemo/blob/master/viewlib/src/main/java/it/codingjam/github/util/UiActionsLiveData.kt) can be used in every `ViewModel` to fire such one-off events. 

Second example can be easily done through an additional subject inside `MvRxStateStore` and subscription inside `withState`

**Comment by gpeal** [comment]
@ATizik We use `selectSubscribe` for this. You will be delivered the initial value and any time it changes. We also have `asyncSubscribe` if it's an async prop to handle the unwrapped success or error values.

We use these to handle things like logging or showing toasts/snackbars.

If this isn't sufficient, can you reopen this with a specific use case?
