### ISSUE TITLE
Support for androidx

### ISSUE THREAD

**Issue by MelbyBaldove** [airbnb/MvRx#86]
Will support for androidx be added anytime soon?

**Comment by MatushkaRossiya** [comment]
Since Lottie has already migrated to androidx and Epoxy is about to do the same thing soon, can we expect a release of MvRx based on androidx in the near future? Especially considering that there are some important bug fixes in the master branch.

**Comment by johnnycube** [comment]
@MatushkaRossiya 
What exactly isn't working for you? I'm currently running MvRx in two androidx projects and have experienced no problems so far

**Comment by melbystyle** [comment]
@johnnycube `BaseMvRxFragment` uses supportv4 fragment

**Comment by johnnycube** [comment]
@MatushkaRossiya 
What about implementing MvRxView Interface in your own base fragment and C&P the code from BaseMvRxFragment in order to achieve compatibility?

**Comment by melbystyle** [comment]
That would work but as much as possible I don't want to vendor code.

**Comment by johnnycube** [comment]
@MatushkaRossiya 
I understand - but in the end its just 3 simple additions to setup the ModelStore. At least easily maintainable even if not your ideal solution.

**Comment by BenSchwab** [comment]
We are working on our androidx migration internally at Airbnb. While I can't make any promises on the timeline, we hope it won't be too long. MvRx will be updated to androidx as part of that migration.

**Comment by L7ColWinters** [comment]
Any update on the migration?

**Comment by jQrgen** [comment]
Probably related to https://github.com/airbnb/MvRx/issues/212

**Comment by tasomaniac** [comment]
Is this closed with 1.0 release?

**Comment by ngallazzi** [comment]
Works perfectly for me with 1.0.1 and 
android.useAndroidX=true
android.enableJetifier=true in Project Properties

**Comment by gpeal** [comment]
1.0 is on androidx
