### ISSUE TITLE
DrawerLayout + generally more examples wanted

### ISSUE THREAD

**Issue by jQrgen** [airbnb/MvRx#93]
Hello

I'm trying to set up a DrawerLayout in the MvRx sample project but i am kind of stuck. 

Totally new to both epoxy and MvRx in general and i have been playing around for a week now learning about the framework and testing components i need to convert our app to MvRx.

**What i am wondering is how you setup a DrawerLayout view using MvRx.** 

Also the current examples are very comprehensive for noobs. Anyone has a minimalist starter available?

// JQ

**Comment by gpeal** [comment]
@jQrgen there is a [Hello World](https://github.com/airbnb/MvRx/tree/master/sample/src/main/java/com/airbnb/mvrx/sample/features/helloworld) example that is about as simple as it gets.

DrawerLayout is just a view that you use within a Fragment so it really shouldn't have anything to do with MvRx or epoxy itself so it's hard to know how to assist without specific questions.
