### ISSUE TITLE
Avoid delivering state's last value when unlocked

### ISSUE THREAD

**Issue by luozejiaqun** [airbnb/MvRx#94]
In the `BaseMvRxViewModel` , I found that all the subscribe method finally call `subscribeLifecycle`, in which `MvRxLifecycleAwareObserver` 's property `alwaysDeliverLastValueWhenUnlocked` is set to true. So when the phone's screen is on and off, the same state value diliver again(the Toast show again). Is there anyway to avoid this?

**Comment by littleGnAl** [comment]
I think you need to invoke the `setState` to reset the state

**Comment by gpeal** [comment]
@BenSchwab @elihart What if we add an optional but default false parameter to `subscribe` and `selectSubscribe` that will only deliver true changes. Otherwise, it will get redelivered in onStart. Everything *should* be ephemeral but some things like logging inherently aren't.
