### ISSUE TITLE
Paging Lib + MvRx

### ISSUE THREAD

**Issue by tallnato** [airbnb/MvRx#98]
Hello 👋 

What would be the recommended (or suggested) way to use the Android Paging Library with MvRx? 

Should put as property of the state the DataFactory, PagedList, LivePagedList? 

I would like to hear your thoughts on this.

Thanks and keep up the great work

**Comment by qbait** [comment]
You use MvRx with `Epoxy`, don't you? To my information, it's implemented there https://github.com/airbnb/epoxy/issues/285

**Comment by gpeal** [comment]
@tallnato Yes, this is mostly just on Epoxy which now supports it.
Thanks @qbait
